<a href="https://colab.research.google.com/github/j156734119/Amazon-reviews-2023-electronics-SFT-DPO/blob/main/Amazon_Review_Alignment_A100%E2%80%94output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Amazon Review Alignment: A100 Smoke -> Formal -> Baselines

Single Colab workflow: first run an isolated A100 smoke test with Qwen3.5-2B, then run the formal A100 online profile, and finally evaluate trained policies together with the configured baselines.

## 1. Mount Drive And Sync The Repo

Training outputs and checkpoints are stored in Google Drive. Before opening this notebook in Colab, push your latest local changes to GitHub `main`; this notebook clones or fast-forwards the Drive workspace to the latest remote commit.

In [1]:
import os
import subprocess
from pathlib import Path

from google.colab import drive

drive.mount("/content/drive")

REPO_URL = "https://github.com/j156734119/Amazon-reviews-2023-electronics-SFT-DPO.git"
REPO_DIR = Path("/content/drive/MyDrive/amazon-review-alignment-workspace/repo")
REPO_DIR.parent.mkdir(parents=True, exist_ok=True)

if (REPO_DIR / ".git").exists():
    status = subprocess.run(
        ["git", "-C", str(REPO_DIR), "status", "--short"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if status:
        print("Preserving Colab-local tracked changes before pull:")
        print(status)
        subprocess.run(
            ["git", "-C", str(REPO_DIR), "stash", "push", "-m", "colab-auto-stash-before-pull"],
            check=True,
        )
    subprocess.run(["git", "-C", str(REPO_DIR), "pull", "--ff-only", "origin", "main"], check=True)
else:
    subprocess.run(["git", "clone", REPO_URL, str(REPO_DIR)], check=True)

os.chdir(REPO_DIR)
print("Repository:", REPO_DIR)
subprocess.run(["git", "log", "-1", "--oneline"], check=True)

Mounted at /content/drive
Preserving Colab-local tracked changes before pull:
M outputs/a100-qwen3.5-2b/evaluation/evaluation_summary.json
 M outputs/a100-qwen3.5-2b/evaluation/judge_decisions.jsonl
 M outputs/a100-qwen3.5-2b/evaluation/judge_pairwise_summary.csv
 M outputs/a100-qwen3.5-2b/evaluation/metrics.csv
 M outputs/a100-qwen3.5-2b/evaluation/metrics.png
 M outputs/a100-qwen3.5-2b/evaluation/report.md
 M outputs/a100-qwen3.5-2b/rlhf/data_manifest.json
 M outputs/a100-qwen3.5-2b/rlhf/grpo_log_history.json
 M outputs/a100-qwen3.5-2b/rlhf/grpo_metrics.json
 M outputs/a100-qwen3.5-2b/rlhf/ppo_log_history.json
 M outputs/a100-qwen3.5-2b/rlhf/ppo_metrics.json
?? a100_mini_results.zip
Repository: /content/drive/MyDrive/amazon-review-alignment-workspace/repo

CompletedProcess(args=['git', 'log', '-1', '--oneline'], returncode=0)

## 2. Install Dependencies

After this cell finishes, use the Colab menu **Runtime -> Restart session**. After restart, continue from the next cell; do not reinstall unless the runtime was reset.

In [2]:
import subprocess
import sys

subprocess.run([sys.executable, "-m", "pip", "uninstall", "-y", "torchao"], check=False)
subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q", "--upgrade", "pip", "setuptools", "wheel"],
    check=True,
)
subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q", "-e", ".[train,eval,dev]"],
    cwd=REPO_DIR,
    check=True,
)
print("Installation complete. Restart the Colab runtime now.")

Installation complete. Restart the Colab runtime now.

## 3. Restore Environment And CLI Helper

Add `OPENAI_API_KEY` in Colab Secrets. `HF_TOKEN` is optional but recommended for Hugging Face download limits. `DEEPSEEK_API_KEY` is only required when running the DeepSeek baseline.

In [1]:
import os
import subprocess
import sys
from pathlib import Path

from google.colab import drive, userdata
from packaging.version import Version

drive.mount("/content/drive", force_remount=False)
REPO_DIR = Path("/content/drive/MyDrive/amazon-review-alignment-workspace/repo")
os.chdir(REPO_DIR)

source_dir = str(REPO_DIR / "src")
if source_dir not in sys.path:
    sys.path.insert(0, source_dir)

for secret_name in ("OPENAI_API_KEY", "HF_TOKEN", "DEEPSEEK_API_KEY"):
    try:
        value = userdata.get(secret_name)
    except Exception:
        value = None
    if value:
        os.environ[secret_name] = value

try:
    import importlib.metadata
    torchao_version = importlib.metadata.version("torchao")
except importlib.metadata.PackageNotFoundError:
    torchao_version = None
if torchao_version is not None:
    print("Removing unused TorchAO:", torchao_version)
    subprocess.run([sys.executable, "-m", "pip", "uninstall", "-y", "torchao"], check=True)


def training_stack_is_usable() -> bool:
    try:
        import amazon_review_alignment
        import bitsandbytes
        import peft
        import transformers
        import trl
    except (ImportError, ModuleNotFoundError):
        return False
    return Version(bitsandbytes.__version__) >= Version("0.46.1")


if not training_stack_is_usable():
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q", "-e", ".[train,eval,dev]"],
        cwd=REPO_DIR,
        check=True,
    )

import amazon_review_alignment
import bitsandbytes
import peft
import transformers
import trl


def cli(*arguments: str, check: bool = True) -> subprocess.CompletedProcess:
    command = [
        sys.executable,
        "-u",
        "-m",
        "amazon_review_alignment.cli",
        *(str(argument) for argument in arguments),
    ]
    print("\n$", " ".join(command), flush=True)
    env = os.environ.copy()
    env["PYTHONPATH"] = source_dir + os.pathsep + env.get("PYTHONPATH", "")
    env["PYTHONUNBUFFERED"] = "1"
    env["PYTHONFAULTHANDLER"] = "1"
    process = subprocess.Popen(
        command,
        cwd=REPO_DIR,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        bufsize=1,
    )
    output_lines = []
    assert process.stdout is not None
    for line in process.stdout:
        print(line, end="", flush=True)
        output_lines.append(line)
    returncode = process.wait()
    result = subprocess.CompletedProcess(command, returncode, stdout="".join(output_lines), stderr=None)
    if check and returncode:
        print("\n===== LAST 200 LINES =====")
        print("".join(output_lines[-200:]))
        raise RuntimeError(f"Command failed with exit code {returncode}: " + " ".join(command))
    return result

print("Package:", Path(amazon_review_alignment.__file__).resolve())
print("Training stack:", transformers.__version__, trl.__version__, peft.__version__, bitsandbytes.__version__)
print("OpenAI key loaded:", bool(os.getenv("OPENAI_API_KEY")))
print("HF token loaded:", bool(os.getenv("HF_TOKEN")))
print("DeepSeek key loaded:", bool(os.getenv("DEEPSEEK_API_KEY")))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Package: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/__init__.py
Training stack: 5.5.4 1.5.1 0.19.1 0.49.2
OpenAI key loaded: True
HF token loaded: True
DeepSeek key loaded: True

## 4. A100 Environment Check

In [2]:
import importlib.metadata

import torch
import transformers
import trl

if not torch.cuda.is_available():
    raise RuntimeError("CUDA is unavailable. Select a Colab GPU runtime.")

gpu_name = torch.cuda.get_device_name(0)
total_gib = torch.cuda.get_device_properties(0).total_memory / 1024**3
print("GPU:", gpu_name)
print(f"VRAM: {total_gib:.2f} GiB")
print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("TRL:", trl.__version__)
print("PEFT:", importlib.metadata.version("peft"))

if "a100" not in gpu_name.lower():
    raise RuntimeError("Expected A100, but Colab assigned: " + gpu_name)
if total_gib < 38:
    raise RuntimeError("Insufficient GPU memory for this A100 profile.")
if not torch.cuda.is_bf16_supported():
    raise RuntimeError("This profile requires BF16 support.")

GPU: NVIDIA A100-SXM4-40GB
VRAM: 39.49 GiB
PyTorch: 2.11.0+cu128
Transformers: 5.5.4
TRL: 1.5.1
PEFT: 0.19.1

## 5. Build The Smoke Config

The smoke config is derived from the formal `rlhf_a100_online_v2.yaml` profile. It still uses Qwen3.5-2B and the A100/BF16 path, but reduces data size, training steps, PPO/GRPO prompt counts, and evaluation samples. Its output directory is isolated from the formal run, so it will not overwrite formal checkpoints.

In [3]:
import json
from pathlib import Path

import yaml

from amazon_review_alignment.config import load_config

FORMAL_CONFIG = "configs/rlhf_a100_online_v2.yaml"
SMOKE_CONFIG_PATH = Path("/content/rlhf_a100_smoke.yaml")

formal = load_config(REPO_DIR / FORMAL_CONFIG)
formal.pop("_config_path", None)

old_root = "outputs/a100-qwen3.5-2b"
smoke_root = "outputs/a100-smoke-qwen3.5-2b"


def replace_output_paths(value):
    if isinstance(value, dict):
        return {key: replace_output_paths(item) for key, item in value.items()}
    if isinstance(value, list):
        return [replace_output_paths(item) for item in value]
    if isinstance(value, str):
        return value.replace(old_root, smoke_root)
    return value


smoke = replace_output_paths(formal)
smoke["project"]["output_dir"] = smoke_root
smoke["data"].update(
    {
        "sample_size": 60,
        "max_scanned_reviews": 20000,
        "rating_targets": {"1": 12, "2": 12, "3": 12, "4": 12, "5": 12},
        "splits": {"train": 42, "validation": 6, "test": 12},
    }
)
smoke["teacher"].update({"pilot_size": 5, "max_estimated_cost_usd": 1.0})
smoke["training"]["sft"]["max_steps"] = 1
smoke["training"]["dpo"]["max_steps"] = 1
smoke["rlhf"].update(
    {
        "human_calibration_samples": 0,
        "ai_reward_train_pairs": 4,
        "ai_reward_validation_pairs": 2,
        "ppo_prompt_count": 4,
    }
)
smoke["rlhf"]["reward"]["max_steps"] = 1
smoke["rlhf"]["ppo"].update({"total_episodes": 4, "gradient_accumulation_steps": 1, "save_steps": 1})
smoke["rlhf"]["grpo"].update({"prompt_count": 4, "num_generations": 2, "generation_batch_size": 2, "max_steps": 1, "save_steps": 1})
smoke["evaluation"].update(
    {
        "max_test_samples": 4,
        "variants": ["base", "sft", "dpo", "ppo", "grpo"],
        "judge_samples_per_pair": 4,
        "judge_pairs": [["sft", "dpo"], ["sft", "ppo"], ["sft", "grpo"], ["ppo", "grpo"]],
    }
)

SMOKE_CONFIG_PATH.write_text(yaml.safe_dump(smoke, sort_keys=False, allow_unicode=True), encoding="utf-8")

print("Smoke config:", SMOKE_CONFIG_PATH)
print("Formal config:", FORMAL_CONFIG)
print("Smoke output:", smoke["project"]["output_dir"])
print("Formal output:", formal["project"]["output_dir"])
print("Formal evaluation variants:", ", ".join(formal["evaluation"]["variants"]))

Smoke config: /content/rlhf_a100_smoke.yaml
Formal config: configs/rlhf_a100_online_v2.yaml
Smoke output: outputs/a100-smoke-qwen3.5-2b
Formal output: outputs/a100-qwen3.5-2b
Formal evaluation variants: base, sft, dpo, ppo, grpo, qwen35_2b_fewshot, nlptown_template, deepseek_v4_pro_fewshot

## 6. A100 Smoke Test

This cell runs the full minimal pipeline in order. If `teacher-batch` is not complete yet, rerun this cell later after the batch finishes. Do not skip smoke and jump directly to the formal run.

In [5]:
import pandas as pd


def output_root_for(config_path: str | Path) -> Path:
    return Path(load_config(config_path)["project"]["output_dir"]).resolve()


def require_teacher_outputs(config_path: str | Path) -> None:
    root = output_root_for(config_path)
    train_preferences = root / "teacher" / "preferences_train.jsonl"
    validation_preferences = root / "teacher" / "preferences_validation.jsonl"
    if not train_preferences.exists() or not validation_preferences.exists():
        raise RuntimeError("Teacher batch is not complete yet. Re-run teacher-batch later, then rerun this cell.")
    print("Teacher train rows:", sum(1 for line in train_preferences.open(encoding="utf-8") if line.strip()))
    print("Teacher validation rows:", sum(1 for line in validation_preferences.open(encoding="utf-8") if line.strip()))


def ensure_teacher_pilot(config_path: str | Path) -> None:
    root = output_root_for(config_path)
    pilot_summary = root / "teacher" / "pilot_summary.json"
    if pilot_summary.exists():
        print("Reusing teacher pilot summary:", pilot_summary)
        return
    cli("teacher-pilot", "--config", str(config_path))


SMOKE_CONFIG = str(SMOKE_CONFIG_PATH)
subprocess.run([sys.executable, "-m", "pytest"], cwd=REPO_DIR, check=True)
cli("prepare-data", "--config", SMOKE_CONFIG)
cli("evaluate", "--config", SMOKE_CONFIG, "--variants", "base", "--force-inference")

if not os.getenv("OPENAI_API_KEY"):
    raise RuntimeError("Add OPENAI_API_KEY to Colab Secrets first.")
ensure_teacher_pilot(SMOKE_CONFIG)
cli("teacher-batch", "--config", SMOKE_CONFIG)
require_teacher_outputs(SMOKE_CONFIG)

cli("train-sft", "--config", SMOKE_CONFIG)
cli("merge-sft", "--config", SMOKE_CONFIG)
cli("train-dpo", "--config", SMOKE_CONFIG)
cli("build-rlhf-data", "--config", SMOKE_CONFIG)
cli("train-reward", "--config", SMOKE_CONFIG)
cli("train-ppo", "--config", SMOKE_CONFIG)
cli("train-grpo", "--config", SMOKE_CONFIG)
cli("evaluate", "--config", SMOKE_CONFIG, "--variants", "base", "sft", "dpo", "ppo", "grpo", "--force-inference")
cli("build-report", "--config", SMOKE_CONFIG)

display(pd.read_csv(output_root_for(SMOKE_CONFIG) / "evaluation" / "metrics.csv"))
print("Smoke report:", output_root_for(SMOKE_CONFIG) / "evaluation" / "report.md")

$ /usr/bin/python3 -u -m amazon_review_alignment.cli prepare-data --config /content/rlhf_a100_smoke.yaml
2026-07-16 11:45:20,069 | INFO | numexpr.utils | NumExpr defaulting to 12 threads.
2026-07-16 11:45:20,534 | INFO | datasets | TensorFlow version 2.20.0 available.
2026-07-16 11:45:20,536 | INFO | datasets | JAX version 0.7.2 available.
2026-07-16 11:45:20,862 | INFO | amazon_review_alignment.data | Streaming reviews from https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl
2026-07-16 11:45:21,606 | INFO | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
2026-07-16 11:45:21,861 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/datasets/McAuley-Lab/Amazon-Reviews-2023/revision/main "HTTP/1.1 200 OK"
2026-07-16 11:45:22,101 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/datasets/McAuley-Lab/Amazon-Reviews-2023/tree/main/raw%2Freview_categories?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-07-16 11:45:22,424 | INFO | httpx | HTTP Request: GET https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl "HTTP/1.1 302 Found"
2026-07-16 11:45:22,450 | INFO | httpx | HTTP Request: GET https://cas-bridge.xethub.hf.co/xet-bridge-us/65af4645d0a5cc99d51642da/28866377eb7aec134fa8b5028e64a9d5de9960a671ef0babc5e0e177e1a96bc1?Expires=1784205922&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jYXMtYnJpZGdlLnhldGh1Yi5oZi5jby94ZXQtYnJpZGdlLXVzLzY1YWY0NjQ1ZDBhNWNjOTlkNTE2NDJkYS8yODg2NjM3N2ViN2FlYzEzNGZhOGI1MDI4ZTY0YTlkNWRlOTk2MGE2NzFlZjBiYWJjNWUwZTE3N2UxYTk2YmMxKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc4NDIwNTkyMn19fV19&Signature=MEQCIBBsEmMiAMXkXiMAoFMqG5Ok20S3C87%7EGw3ZDai5rPz-AiAwYDOlPFlmuH6EIgLdrS5D%7Eml7kNa1Kg9bXQ-Tq7FvXA__&Key-Pair-Id=K3EPXBYC3CKDRZ&X-Xet-Cas-Uid=69de1b2958833616a2cc4a2f&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Electronics.jsonl%3B+filename%3D%22Electronics.jsonl%22%3B&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=cas%2F20260716%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260716T114522Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=ae49ec43fcc096e2034a7f1fa88ec95c97c8190e357c624e921dffe139371a31 "HTTP/1.1 206 Partial Content"
2026-07-16 11:45:24,620 | INFO | httpx | HTTP Request: GET https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl "HTTP/1.1 302 Found"
2026-07-16 11:45:24,629 | INFO | httpx | HTTP Request: GET https://cas-bridge.xethub.hf.co/xet-bridge-us/65af4645d0a5cc99d51642da/28866377eb7aec134fa8b5028e64a9d5de9960a671ef0babc5e0e177e1a96bc1?Expires=1784205924&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jYXMtYnJpZGdlLnhldGh1Yi5oZi5jby94ZXQtYnJpZGdlLXVzLzY1YWY0NjQ1ZDBhNWNjOTlkNTE2NDJkYS8yODg2NjM3N2ViN2FlYzEzNGZhOGI1MDI4ZTY0YTlkNWRlOTk2MGE2NzFlZjBiYWJjNWUwZTE3N2UxYTk2YmMxKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc4NDIwNTkyNH19fV19&Signature=MEQCIAuwdiyDLUtHQfVao8d8yrqBtFF6v%7E%7E%7EWfOY8IznlFwWAiBtgmgh2oxHmMOIbsP2zDWmLfPkFAV4%7E-BGrGdRs2afsg__&Key-Pair-Id=K3EPXBYC3CKDRZ&X-Xet-Cas-Uid=69de1b2958833616a2cc4a2f&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Electronics.jsonl%3B+filename%3D%22Electronics.jsonl%22%3B&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=cas%2F20260716%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260716T114524Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=9e4d80ec3e8ec688c0b86bdbe785c4466965c60f75b19a3c24b1ca3e04a09e40 "HTTP/1.1 206 Partial Content"
2026-07-16 11:45:24,811 | INFO | amazon_review_alignment.data | Prepared 60 reviews under /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-smoke-qwen3.5-2b/data
{
  "source_url": "https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl",
  "scanned_reviews": 359,
  "selected_reviews": 60,
  "selection_policy": "unique normalized text and at most one review per parent_asin",
  "rating_counts": {
    "1": 12,
    "2": 12,
    "3": 12,
    "4": 12,
    "5": 12
  },
  "split_sizes": {
    "train": 42,
    "validation": 6,
    "test": 12
  },
  "split_rating_counts": {
    "train": {
      "1": 8,
      "2": 8,
      "3": 8,
      "4": 9,
      "5": 9
    },
    "validation": {
      "1": 2,
      "2": 1,
      "3": 1,
      "4": 1,
      "5": 1
    },
    "test": {
      "1": 2,
      "2": 3,
      "3": 3,
      "4": 2,
      "5": 2
    }
  }
}

$ /usr/bin/python3 -u -m amazon_review_alignment.cli evaluate --config /content/rlhf_a100_smoke.yaml --variants base --force-inference
2026-07-16 11:45:25,881 | INFO | numexpr.utils | NumExpr defaulting to 12 threads.
2026-07-16 11:45:32,640 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:45:32,646 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:45:32,913 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:45:32,919 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 11:45:33,162 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:45:33,168 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 11:45:33,404 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-16 11:45:33,635 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-16 11:45:35,629 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B "HTTP/1.1 200 OK"
2026-07-16 11:45:35,984 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:45:35,991 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:45:36,696 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:45:36,702 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:45:39,233 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-07-16 11:45:39,480 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors.index.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:45:39,489 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/model.safetensors.index.json "HTTP/1.1 200 OK"
2026-07-16 11:45:39,724 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors-00001-of-00001.safetensors "HTTP/1.1 302 Found"
The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

Loading weights:   0%|          | 0/320 [00:00<?, ?it/s]
Loading weights:   0%|          | 1/320 [00:00<01:21,  3.90it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Loading weights:   9%|▉         | 28/320 [00:00<00:03, 96.71it/s]
Loading weights:  21%|██        | 66/320 [00:00<00:01, 189.25it/s]
Loading weights:  31%|███▏      | 100/320 [00:00<00:00, 234.13it/s]
Loading weights:  45%|████▌     | 145/320 [00:00<00:00, 299.70it/s]
Loading weights:  57%|█████▋    | 181/320 [00:00<00:00, 316.39it/s]
Loading weights:  68%|██████▊   | 219/320 [00:00<00:00, 335.17it/s]
Loading weights:  80%|███████▉  | 255/320 [00:00<00:00, 332.49it/s]
Loading weights:  91%|█████████▏| 292/320 [00:01<00:00, 342.83it/s]
Loading weights: 100%|██████████| 320/320 [00:01<00:00, 274.89it/s]
2026-07-16 11:45:42,000 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/generation_config.json "HTTP/1.1 404 Not Found"
2026-07-16 11:45:42,254 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:45:42,261 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:45:42,491 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
{
  "local_metrics": [
    {
      "variant": "base",
      "examples": 4,
      "schema_valid_rate": 1.0,
      "evidence_grounded_rate": 1.0,
      "word_limit_ok_rate": 1.0,
      "instruction_following_rate": 1.0
    }
  ]
}
Reusing teacher pilot summary: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-smoke-qwen3.5-2b/teacher/pilot_summary.json

$ /usr/bin/python3 -u -m amazon_review_alignment.cli teacher-batch --config /content/rlhf_a100_smoke.yaml
2026-07-16 11:46:12,343 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/batches/batch_6a58c2f200648190ad8887fbae630406 "HTTP/1.1 200 OK"
2026-07-16 11:46:13,595 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/files/file-NMneqdvyF8Unvm6XorGf39/content "HTTP/1.1 200 OK"
{
  "completed": {
    "train": 15,
    "validation": 3
  },
  "quarantined": 30,
  "usage": {
    "input_tokens": 18694,
    "output_tokens": 6296
  },
  "batch_cost_usd": 0.021176
}
Teacher train rows: 15
Teacher validation rows: 3

$ /usr/bin/python3 -u -m amazon_review_alignment.cli train-sft --config /content/rlhf_a100_smoke.yaml
2026-07-16 11:46:14,878 | INFO | numexpr.utils | NumExpr defaulting to 12 threads.
2026-07-16 11:46:15,350 | INFO | datasets | TensorFlow version 2.20.0 available.
2026-07-16 11:46:15,352 | INFO | datasets | JAX version 0.7.2 available.
2026-07-16 11:46:25,653 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:25,659 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:46:25,924 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:25,931 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 11:46:26,164 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:26,171 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 11:46:26,424 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-16 11:46:26,673 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-16 11:46:28,530 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B "HTTP/1.1 200 OK"
2026-07-16 11:46:28,920 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:28,928 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:46:29,190 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:29,200 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:46:31,774 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-07-16 11:46:32,009 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors.index.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:32,017 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/model.safetensors.index.json "HTTP/1.1 200 OK"
2026-07-16 11:46:32,270 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors-00001-of-00001.safetensors "HTTP/1.1 302 Found"
The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

Loading weights:   0%|          | 0/320 [00:00<?, ?it/s]
Loading weights:   0%|          | 1/320 [00:00<01:21,  3.91it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Loading weights:   8%|▊         | 27/320 [00:00<00:03, 95.67it/s]
Loading weights:  20%|██        | 65/320 [00:00<00:01, 189.55it/s]
Loading weights:  31%|███       | 99/320 [00:00<00:00, 233.28it/s]
Loading weights:  44%|████▍     | 142/320 [00:00<00:00, 290.88it/s]
Loading weights:  55%|█████▍    | 175/320 [00:00<00:00, 302.20it/s]
Loading weights:  66%|██████▌   | 210/320 [00:00<00:00, 314.46it/s]
Loading weights:  79%|███████▉  | 252/320 [00:00<00:00, 341.09it/s]
Loading weights:  91%|█████████ | 290/320 [00:01<00:00, 350.19it/s]
Loading weights: 100%|██████████| 320/320 [00:01<00:00, 272.17it/s]
2026-07-16 11:46:34,207 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/generation_config.json "HTTP/1.1 404 Not Found"
2026-07-16 11:46:34,446 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:34,452 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:46:34,693 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Adding EOS to train dataset:   0%|          | 0/15 [00:00<?, ? examples/s]
Adding EOS to train dataset: 100%|██████████| 15/15 [00:00<00:00, 3730.92 examples/s]

Tokenizing train dataset:   0%|          | 0/15 [00:00<?, ? examples/s]
Tokenizing train dataset: 100%|██████████| 15/15 [00:00<00:00, 450.27 examples/s]

Adding EOS to eval dataset:   0%|          | 0/3 [00:00<?, ? examples/s]
Adding EOS to eval dataset: 100%|██████████| 3/3 [00:00<00:00, 1362.23 examples/s]

Tokenizing eval dataset:   0%|          | 0/3 [00:00<?, ? examples/s]
Tokenizing eval dataset: 100%|██████████| 3/3 [00:00<00:00, 352.46 examples/s]
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 248046, 'pad_token_id': 248044}.
2026-07-16 11:46:36,796 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/telemetry/trl/SFTTrainer "HTTP/1.1 200 OK"

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:08<00:00,  8.04s/it]

  0%|          | 0/1 [00:00<?, ?it/s]



{'eval_loss': '1.328', 'eval_runtime': '0.3566', 'eval_samples_per_second': '8.412', 'eval_steps_per_second': '2.804', 'eval_entropy': '1.041', 'eval_num_tokens': '3646', 'eval_mean_token_accuracy': '0.6534', 'epoch': '1'}

100%|██████████| 1/1 [00:08<00:00,  8.04s/it]

100%|██████████| 1/1 [00:00<00:00, 1280.70it/s]

                                               2026-07-16 11:46:45,622 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:45,628 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:46:45,858 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:45,864 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"


{'train_runtime': '9.703', 'train_samples_per_second': '1.649', 'train_steps_per_second': '0.103', 'train_loss': '1.203', 'epoch': '1'}

100%|██████████| 1/1 [00:09<00:00,  8.04s/it]
100%|██████████| 1/1 [00:09<00:00,  9.70s/it]
2026-07-16 11:46:46,883 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:46,892 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:46:47,144 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 11:46:47,150 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 11:46:47,801 | INFO | amazon_review_alignment.train_sft | Saved SFT adapter to /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-smoke-qwen3.5-2b/models/sft
/content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-smoke-qwen3.5-2b/models/sft

$ /usr/bin/python3 -u -m amazon_review_alignment.cli merge-sft --config /content/rlhf_a100_smoke.yaml

,variant,examples,schema_valid_rate,evidence_grounded_rate,word_limit_ok_rate,instruction_following_rate
0,base,4,1.0,1.0,1.0,1.0
1,sft,4,1.0,1.0,1.0,1.0
2,dpo,4,1.0,1.0,1.0,1.0
3,ppo,4,1.0,1.0,1.0,1.0
4,grpo,4,1.0,1.0,1.0,1.0

Smoke report: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-smoke-qwen3.5-2b/evaluation/report.md

## 7. Formal Training: Data And Teacher Preferences

The formal profile uses `configs/rlhf_a100_online_v2.yaml`, including DPO v2, 1,024 shared PPO/GRPO prompts, and baseline evaluation settings. If the batch is still running, you can disconnect the GPU runtime and resume from this cell later.

In [7]:
import json
from pathlib import Path

teacher_dir = FORMAL_ROOT / "teacher"
print("Teacher dir:", teacher_dir)
print("Exists:", teacher_dir.exists())

for name in [
    "pilot_summary.json",
    "batch_state.json",
    "batch_prepare_summary.json",
    "batch_summary.json",
    "batch_quarantine.jsonl",
]:
    path = teacher_dir / name
    print("\n==", name, "==")
    print("exists:", path.exists())
    if path.exists():
        text = path.read_text(encoding="utf-8")
        print(text[:4000])

Teacher dir: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/teacher
Exists: True

== pilot_summary.json ==
exists: True
{
  "requested_items": 100,
  "completed_items": 53,
  "quarantined_items": 47,
  "usage": {
    "input_tokens": 23026,
    "output_tokens": 7023
  },
  "pilot_standard_cost_usd": 0.048873,
  "projected_batch_items": 4000,
  "projected_batch_usage": {
    "input_tokens": 1737811,
    "output_tokens": 530038
  },
  "projected_batch_cost_usd": 1.844265,
  "price_assumptions": {
    "input_price_per_million": 0.75,
    "output_price_per_million": 4.5,
    "batch_discount_multiplier": 0.5
  }
}

== batch_state.json ==
exists: True
{
  "id": "batch_6a2f615a5d4c81908c06a49ef4bae222",
  "completion_window": "24h",
  "created_at": 1781490010,
  "endpoint": "/v1/responses",
  "input_file_id": "file-9wFHWz6wkAqSnkxCZkm5Qu",
  "object": "batch",
  "status": "completed",
  "cancelled_at": null,
  "cancelling_at": null,
  "completed_at": 1781490711,
  "error_file_id": null,
  "errors": null,
  "expired_at": null,
  "expires_at": 1781576410,
  "failed_at": null,
  "finalizing_at": 1781490448,
  "in_progress_at": 1781490073,
  "metadata": {
    "project": "amazon-review-alignment"
  },
  "model": "gpt-5.4-mini-2026-03-17",
  "output_file_id": "file-YSRyMTNErQUrNJ3LpVLVpA",
  "request_counts": {
    "completed": 4000,
    "failed": 0,
    "total": 4000
  },
  "usage": {
    "input_tokens": 1786035,
    "input_tokens_details": {
      "cached_tokens": 0
    },
    "output_tokens": 555984,
    "output_tokens_details": {
      "reasoning_tokens": 0
    },
    "total_tokens": 2342019
  }
}

== batch_prepare_summary.json ==
exists: False

== batch_summary.json ==
exists: True
{
  "completed": {
    "train": 1033,
    "validation": 130
  },
  "quarantined": 2837,
  "usage": {
    "input_tokens": 1786035,
    "output_tokens": 555984
  },
  "batch_cost_usd": 1.920727
}

== batch_quarantine.jsonl ==
exists: True
{"custom_id": "train:b03df6a45118d025631c:fabricated_evidence", "error": "Chosen evidence is not grounded in the review.", "raw_result": {"id": "batch_req_6a2f63119b408190a3b4e25d29707d0b", "custom_id": "train:b03df6a45118d025631c:fabricated_evidence", "response": {"status_code": 200, "request_id": "d263f825-770e-46a9-a957-f94cd433cf36", "body": {"id": "resp_006f8d6c3410c64b006a2f61bf1a54819596e45d1837418907", "object": "response", "created_at": 1781490111, "status": "completed", "background": false, "billing": {"payer": "developer"}, "completed_at": 1781490112, "error": null, "frequency_penalty": 0.0, "incomplete_details": null, "instructions": null, "max_output_tokens": 700, "max_tool_calls": null, "model": "gpt-5.4-mini-2026-03-17", "moderation": null, "output": [{"id": "msg_006f8d6c3410c64b006a2f61bfd78c81959e46a40b9db05132", "type": "message", "status": "completed", "content": [{"type": "output_text", "annotations": [], "logprobs": [], "text": "{\"chosen\":{\"sentiment\":\"positive\",\"evidence\":[\"\\\"It's nice and small\\\"\",\"\\\"The mouse is very responsive.\\\"\"],\"analysis\":\"The review is overall positive. It praises the mouse as small, responsive, sturdy, and easy to set up, and also says the buttons click well. The only caution is that it may not suit big hands and could break if dropped from a height.\"},\"rejected\":\"{\\\"sentiment\\\":\\\"positive\\\",\\\"evidence\\\":[\\\"great battery life\\\",\\\"works with all devices\\\"],\\\"analysis\\\":\\\"The reviewer likes the compact design and says it feels durable. It is also easy to install and good for travel.\\\"}\",\"defect_type\":\"fabricated_evidence\"}"}], "phase": "final_answer", "role": "assistant"}], "parallel_tool_calls": true, "presence_penalty": 0.0, "previous_response_id": null, "prompt_cache_key": null, "prompt_cache_retention": "24h", "reasoning": {"context": "current_turn", "effort": "none", "summary": null}, "safety_identifier": null, "service_tier": "default", "store": true, "temperature": 1.0, "text": {"format": {"type": "json_schema", "description": null, "name": "teacher_preference", "schema": {"$defs": {"DefectType": {"enum": ["wrong_sentiment", "fabricated_evidence", "over_inference", "format_error", "irrelevant_verbose"], "title": "DefectType", "type": "string"}, "ReviewAnalysis": {"additionalProperties": false, "properties": {"sentiment": {"$ref": "#/$defs/Sentiment"}, "evidence": {"items": {"type": "string"}, "maxItems": 2, "minItems": 1, "title": "Evidence", "type": "array"}, "analysis": {"title": "Analysis", "type": "string"}}, "required": ["sentiment", "evidence", "analysis"], "title": "ReviewAnalysis", "type": "object"}, "Sentiment": {"enum": ["negative", "neutral", "positive"], "title": "Sentiment", "type": "string"}}, "additionalProperties": false, "properties": {"chosen": {"$ref": "#/$defs/ReviewAnalysis"}, "rejected": {"title": "Rejected", "type": "string"}, "defect_type": {"$ref": "#/$defs/DefectType"}}, "required": ["chosen", "rejected", "defect_type"], "title": "TeacherPreference", "type": "object"}, "strict": true}, "verbosity": "medium"}, "tool_choice": "auto", "tools": [], "top_logprobs": 0, "top_p": 0.98, "truncation": "disabled", "usage": {"input_tokens": 406, "input_tokens_details": {"cached_tokens": 0}, "output_tokens": 151, "output_tokens_details": {"reasoning_tokens": 0}, "total_tokens": 557}, "user": null, "metadata": {}}}, "error": null}}
{"custom_id": "train:051c2e4340fea08f9455:irrelevant_verbose", "error": "Teacher returned a different defect_type than requested.", "raw_result": {"id": "batch_req_6a2f6311a35c8190b66e6f046f8bbba9", "custom_id": "train:051c2e4340fea08f9455:irrelevant_verbose", "response": {"status_code": 200, "request_id": "f0a9c6d7-577d-4274-ac2e-2d7b9c4a7f7a", "body": {"id": "resp_00bdfffeb4549b69006a2f61c8cae08195ba41d2d88bdacb2c", "object": "response", "created_at": 1781490120, "status": "completed", "background": false, "billing": {"payer": "developer"}, "completed_at": 1781490122, "error

In [8]:
cli("teacher-batch", "--config", FORMAL_CONFIG, "--verbose", check=False)

$ /usr/bin/python3 -u -m amazon_review_alignment.cli teacher-batch --config configs/rlhf_a100_online_v2.yaml --verbose
2026-07-16 12:02:58,943 | DEBUG | openai._base_client | Request options: {'method': 'get', 'url': '/batches/batch_6a2f615a5d4c81908c06a49ef4bae222', 'security': {'bearer_auth': True}}
2026-07-16 12:02:58,945 | DEBUG | openai._base_client | Sending HTTP Request: GET https://api.openai.com/v1/batches/batch_6a2f615a5d4c81908c06a49ef4bae222
2026-07-16 12:02:58,946 | DEBUG | httpcore.connection | connect_tcp.started host='api.openai.com' port=443 local_address=None timeout=5.0 socket_options=None
2026-07-16 12:02:58,953 | DEBUG | httpcore.connection | connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7d8eb75b77d0>
2026-07-16 12:02:58,953 | DEBUG | httpcore.connection | start_tls.started ssl_context=<ssl.SSLContext object at 0x7d8eb8032bd0> server_hostname='api.openai.com' timeout=5.0
2026-07-16 12:02:58,960 | DEBUG | httpcore.connection | start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7d8eb7b33b90>
2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | send_request_headers.started request=<Request [b'GET']>
2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | send_request_headers.complete
2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | send_request_body.started request=<Request [b'GET']>
2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | send_request_body.complete
2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | receive_response_headers.started request=<Request [b'GET']>
2026-07-16 12:02:59,229 | DEBUG | httpcore.http11 | receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Thu, 16 Jul 2026 12:02:59 GMT'), (b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Server', b'cloudflare'), (b'openai-version', b'2020-10-01'), (b'openai-organization', b'personal-wjlt5f'), (b'openai-project', b'proj_563bG7FnxU3biDL35o8XM6he'), (b'x-request-id', b'req_2554a6a3dfe3441289abd57cdfb1548b'), (b'openai-processing-ms', b'24'), (b'x-openai-proxy-wasm', b'v0.1'), (b'access-control-expose-headers', b'X-Request-ID'), (b'Access-Control-Expose-Headers', b'CF-Ray'), (b'cf-cache-status', b'DYNAMIC'), (b'set-cookie', b'__cf_bm=XBOPavmgCiSBTVgx52i4Fa0jA9D_Cmd3ZQmKShnEwX0-1784203378.9645562-1.0.1.1-RqGaw.1GxTLRKDn.Wo4OxwoseBiYohh2jaxIRY1h6kwUlG10jU4PUAMZebZQb663koA2jfJEijxf0IxTAykn5ifEl_41sYj6IJOaxMteYFq6wU4NpyTnTcUrl54gLGx3; HttpOnly; SameSite=None; Secure; Path=/; Domain=api.openai.com; Expires=Thu, 16 Jul 2026 12:32:59 GMT'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'X-Content-Type-Options', b'nosniff'), (b'Content-Encoding', b'br'), (b'CF-RAY', b'a1c0dc6e8809fd29-SIN'), (b'alt-svc', b'h3=":443"; ma=86400')])
2026-07-16 12:02:59,229 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/batches/batch_6a2f615a5d4c81908c06a49ef4bae222 "HTTP/1.1 200 OK"
2026-07-16 12:02:59,230 | DEBUG | httpcore.http11 | receive_response_body.started request=<Request [b'GET']>
2026-07-16 12:02:59,230 | DEBUG | httpcore.http11 | receive_response_body.complete
2026-07-16 12:02:59,230 | DEBUG | httpcore.http11 | response_closed.started
2026-07-16 12:02:59,230 | DEBUG | httpcore.http11 | response_closed.complete
2026-07-16 12:02:59,230 | DEBUG | openai._base_client | HTTP Response: GET https://api.openai.com/v1/batches/batch_6a2f615a5d4c81908c06a49ef4bae222 "200 OK" Headers([('date', 'Thu, 16 Jul 2026 12:02:59 GMT'), ('content-type', 'application/json'), ('transfer-encoding', 'chunked'), ('connection', 'keep-alive'), ('server', 'cloudflare'), ('openai-version', '2020-10-01'), ('openai-organization', 'personal-wjlt5f'), ('openai-project', 'proj_563bG7FnxU3biDL35o8XM6he'), ('x-request-id', 'req_2554a6a3dfe3441289abd57cdfb1548b'), ('openai-processing-ms', '24'), ('x-openai-proxy-wasm', 'v0.1'), ('access-control-expose-headers', 'X-Request-ID'), ('access-control-expose-headers', 'CF-Ray'), ('cf-cache-status', 'DYNAMIC'), ('set-cookie', '__cf_bm=XBOPavmgCiSBTVgx52i4Fa0jA9D_Cmd3ZQmKShnEwX0-1784203378.9645562-1.0.1.1-RqGaw.1GxTLRKDn.Wo4OxwoseBiYohh2jaxIRY1h6kwUlG10jU4PUAMZebZQb663koA2jfJEijxf0IxTAykn5ifEl_41sYj6IJOaxMteYFq6wU4NpyTnTcUrl54gLGx3; HttpOnly; SameSite=None; Secure; Path=/; Domain=api.openai.com; Expires=Thu, 16 Jul 2026 12:32:59 GMT'), ('strict-transport-security', 'max-age=31536000; includeSubDomains; preload'), ('x-content-type-options', 'nosniff'), ('content-encoding', 'br'), ('cf-ray', 'a1c0dc6e8809fd29-SIN'), ('alt-svc', 'h3=":443"; ma=86400')])
2026-07-16 12:02:59,230 | DEBUG | openai._base_client | request_id: req_2554a6a3dfe3441289abd57cdfb1548b
2026-07-16 12:02:59,242 | DEBUG | openai._base_client | Request options: {'method': 'get', 'url': '/files/file-YSRyMTNErQUrNJ3LpVLVpA/content', 'headers': {'Accept': 'application/binary'}, 'security': {'bearer_auth': True}}
2026-07-16 12:02:59,242 | DEBUG | openai._base_client | Sending HTTP Request: GET https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content
2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | send_request_headers.started request=<Request [b'GET']>
2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | send_request_headers.complete
2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | send_request_body.started request=<Request [b'GET']>
2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | send_request_body.complete
2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | receive_response_headers.started request=<Request [b'GET']>
2026-07-16 12:02:59,566 | DEBUG | httpcore.http11 | receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Date', b'Thu, 16 Jul 2026 12:02:59 GMT'), (b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Server', b'cloudflare'), (b'access-control-allow-origin', b'*'), (b'x-request-id', b'req_00654453048e4578ab292a9467ba1e1e'), (b'openai-processing-ms', b'65'), (b'openai-version', b'2020-10-01'), (b'openai-organization', b'personal-wjlt5f'), (b'openai-project', b'proj_563bG7FnxU3biDL35o8XM6he'), (b'x-openai-proxy-wasm', b'v0.1'), (b'cf-cache-status', b'DYNAMIC'), (b'Access-Control-Expose-Headers', b'CF-Ray'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'X-Content-Type-Options', b'nosniff'), (b'Content-Encoding', b'br'), (b'CF-RAY', b'a1c0dc704d73fd29-SIN'), (b'alt-svc', b'h3=":443"; ma=86400')])
2026-07-16 12:02:59,567 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content "HTTP/1.1 404 Not Found"
2026-07-16 12:02:59,567 | DEBUG | httpcore.http11 | receive_response_body.started request=<Request [b'GET']>
2026-07-16 12:02:59,567 | DEBUG | httpcore.http11 | receive_response_body.complete
2026-07-16 12:02:59,567 | DEBUG | httpcore.http11 | response_closed.started
2026-07-16 12:02:59,567 | DEBUG | httpcore.http11 | response_closed.complete
2026-07-16 12:02:59,567 | DEBUG | openai._base_client | HTTP Response: GET https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content "404 Not Found" Headers({'date': 'Thu, 16 Jul 2026 12:02:59 GMT', 'content-type': 'application/json', 'transfer-encoding': 'chunked', 'connection': 'keep-alive', 'server': 'cloudflare', 'access-control-allow-origin': '*', 'x-request-id': 'req_00654453048e4578ab292a9467ba1e1e', 'openai-processing-ms': '65', 'openai-version': '2020-10-01', 'openai-organization': 'personal-wjlt5f', 'openai-project': 'proj_563bG7FnxU3biDL35o8XM6he', 'x-openai-proxy-wasm': 'v0.1', 'cf-cache-status': 'DYNAMIC', 'access-control-expose-headers': 'CF-Ray', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'content-encoding': 'br', 'cf-ray': 'a1c0dc704d73fd29-SIN', 'alt-svc': 'h3=":443"; ma=86400'})
2026-07-16 12:02:59,568 | DEBUG | openai._base_client | request_id: req_00654453048e4578ab292a9467ba1e1e
2026-07-16 12:02:59,568 | DEBUG | openai._base_client | Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1085, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/dist-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
2026-07-16 12:02:59,571 | DEBUG | openai._base_client | Not retrying
2026-07-16 12:02:59,571 | DEBUG | openai._base_client | Re-raising status error
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 215, in <module>
    main()
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 211, in main
    _print_result(command_handlers[args.command]())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 136, in <lambda>
    command_handlers[args.command] = lambda: run_teacher_batch(config, args.prepare_only)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/teacher.py", line 369, in run_teacher_batch
    raw_text = client.files.content(output_file_id).text
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/resources/files.py", line 316, in content
    return self._get(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1263, in get
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1105, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'No such File object: file-YSRyMTNErQUrNJ3LpVLVpA', 'type': 'invalid_request_error', 'param': 'id', 'code': None}, 'detail': {'message': 'No such File object: file-YSRyMTNErQUrNJ3LpVLVpA', 'code': None}}
2026-07-16 12:02:59,706 | DEBUG | httpcore.connection | close.started
2026-07-16 12:02:59,706 | DEBUG | httpcore.connection | close.complete

CompletedProcess(args=['/usr/bin/python3', '-u', '-m', 'amazon_review_alignment.cli', 'teacher-batch', '--config', 'configs/rlhf_a100_online_v2.yaml', '--verbose'], returncode=1, stdout='2026-07-16 12:02:58,943 | DEBUG | openai._base_client | Request options: {\'method\': \'get\', \'url\': \'/batches/batch_6a2f615a5d4c81908c06a49ef4bae222\', \'security\': {\'bearer_auth\': True}}\n2026-07-16 12:02:58,945 | DEBUG | openai._base_client | Sending HTTP Request: GET https://api.openai.com/v1/batches/batch_6a2f615a5d4c81908c06a49ef4bae222\n2026-07-16 12:02:58,946 | DEBUG | httpcore.connection | connect_tcp.started host=\'api.openai.com\' port=443 local_address=None timeout=5.0 socket_options=None\n2026-07-16 12:02:58,953 | DEBUG | httpcore.connection | connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7d8eb75b77d0>\n2026-07-16 12:02:58,953 | DEBUG | httpcore.connection | start_tls.started ssl_context=<ssl.SSLContext object at 0x7d8eb8032bd0> server_hostname=\'api.openai.com\' timeout=5.0\n2026-07-16 12:02:58,960 | DEBUG | httpcore.connection | start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7d8eb7b33b90>\n2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | send_request_headers.started request=<Request [b\'GET\']>\n2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | send_request_headers.complete\n2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | send_request_body.started request=<Request [b\'GET\']>\n2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | send_request_body.complete\n2026-07-16 12:02:58,960 | DEBUG | httpcore.http11 | receive_response_headers.started request=<Request [b\'GET\']>\n2026-07-16 12:02:59,229 | DEBUG | httpcore.http11 | receive_response_headers.complete return_value=(b\'HTTP/1.1\', 200, b\'OK\', [(b\'Date\', b\'Thu, 16 Jul 2026 12:02:59 GMT\'), (b\'Content-Type\', b\'application/json\'), (b\'Transfer-Encoding\', b\'chunked\'), (b\'Connection\', b\'keep-alive\'), (b\'Server\', b\'cloudflare\'), (b\'openai-version\', b\'2020-10-01\'), (b\'openai-organization\', b\'personal-wjlt5f\'), (b\'openai-project\', b\'proj_563bG7FnxU3biDL35o8XM6he\'), (b\'x-request-id\', b\'req_2554a6a3dfe3441289abd57cdfb1548b\'), (b\'openai-processing-ms\', b\'24\'), (b\'x-openai-proxy-wasm\', b\'v0.1\'), (b\'access-control-expose-headers\', b\'X-Request-ID\'), (b\'Access-Control-Expose-Headers\', b\'CF-Ray\'), (b\'cf-cache-status\', b\'DYNAMIC\'), (b\'set-cookie\', b\'__cf_bm=XBOPavmgCiSBTVgx52i4Fa0jA9D_Cmd3ZQmKShnEwX0-1784203378.9645562-1.0.1.1-RqGaw.1GxTLRKDn.Wo4OxwoseBiYohh2jaxIRY1h6kwUlG10jU4PUAMZebZQb663koA2jfJEijxf0IxTAykn5ifEl_41sYj6IJOaxMteYFq6wU4NpyTnTcUrl54gLGx3; HttpOnly; SameSite=None; Secure; Path=/; Domain=api.openai.com; Expires=Thu, 16 Jul 2026 12:32:59 GMT\'), (b\'Strict-Transport-Security\', b\'max-age=31536000; includeSubDomains; preload\'), (b\'X-Content-Type-Options\', b\'nosniff\'), (b\'Content-Encoding\', b\'br\'), (b\'CF-RAY\', b\'a1c0dc6e8809fd29-SIN\'), (b\'alt-svc\', b\'h3=":443"; ma=86400\')])\n2026-07-16 12:02:59,229 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/batches/batch_6a2f615a5d4c81908c06a49ef4bae222 "HTTP/1.1 200 OK"\n2026-07-16 12:02:59,230 | DEBUG | httpcore.http11 | receive_response_body.started request=<Request [b\'GET\']>\n2026-07-16 12:02:59,230 | DEBUG | httpcore.http11 | receive_response_body.complete\n2026-07-16 12:02:59,230 | DEBUG | httpcore.http11 | response_closed.started\n2026-07-16 12:02:59,230 | DEBUG | httpcore.http11 | response_closed.complete\n2026-07-16 12:02:59,230 | DEBUG | openai._base_client | HTTP Response: GET https://api.openai.com/v1/batches/batch_6a2f615a5d4c81908c06a49ef4bae222 "200 OK" Headers([(\'date\', \'Thu, 16 Jul 2026 12:02:59 GMT\'), (\'content-type\', \'application/json\'), (\'transfer-encoding\', \'chunked\'), (\'connection\', \'keep-alive\'), (\'server\', \'cloudflare\'), (\'openai-version\', \'2020-10-01\'), (\'openai-organization\', \'personal-wjlt5f\'), (\'openai-project\', \'proj_563bG7FnxU3biDL35o8XM6he\'), (\'x-request-id\', \'req_2554a6a3dfe3441289abd57cdfb1548b\'), (\'openai-processing-ms\', \'24\'), (\'x-openai-proxy-wasm\', \'v0.1\'), (\'access-control-expose-headers\', \'X-Request-ID\'), (\'access-control-expose-headers\', \'CF-Ray\'), (\'cf-cache-status\', \'DYNAMIC\'), (\'set-cookie\', \'__cf_bm=XBOPavmgCiSBTVgx52i4Fa0jA9D_Cmd3ZQmKShnEwX0-1784203378.9645562-1.0.1.1-RqGaw.1GxTLRKDn.Wo4OxwoseBiYohh2jaxIRY1h6kwUlG10jU4PUAMZebZQb663koA2jfJEijxf0IxTAykn5ifEl_41sYj6IJOaxMteYFq6wU4NpyTnTcUrl54gLGx3; HttpOnly; SameSite=None; Secure; Path=/; Domain=api.openai.com; Expires=Thu, 16 Jul 2026 12:32:59 GMT\'), (\'strict-transport-security\', \'max-age=31536000; includeSubDomains; preload\'), (\'x-content-type-options\', \'nosniff\'), (\'content-encoding\', \'br\'), (\'cf-ray\', \'a1c0dc6e8809fd29-SIN\'), (\'alt-svc\', \'h3=":443"; ma=86400\')])\n2026-07-16 12:02:59,230 | DEBUG | openai._base_client | request_id: req_2554a6a3dfe3441289abd57cdfb1548b\n2026-07-16 12:02:59,242 | DEBUG | openai._base_client | Request options: {\'method\': \'get\', \'url\': \'/files/file-YSRyMTNErQUrNJ3LpVLVpA/content\', \'headers\': {\'Accept\': \'application/binary\'}, \'security\': {\'bearer_auth\': True}}\n2026-07-16 12:02:59,242 | DEBUG | openai._base_client | Sending HTTP Request: GET https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content\n2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | send_request_headers.started request=<Request [b\'GET\']>\n2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | send_request_headers.complete\n2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | send_request_body.started request=<Request [b\'GET\']>\n2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | send_request_body.complete\n2026-07-16 12:02:59,243 | DEBUG | httpcore.http11 | receive_response_headers.started request=<Request [b\'GET\']>\n2026-07-16 12:02:59,566 | DEBUG | httpcore.http11 | receive_response_headers.complete return_value=(b\'HTTP/1.1\', 404, b\'Not Found\', [(b\'Date\', b\'Thu, 16 Jul 2026 12:02:59 GMT\'), (b\'Content-Type\', b\'application/json\'), (b\'Transfer-Encoding\', b\'chunked\'), (b\'Connection\', b\'keep-alive\'), (b\'Server\', b\'cloudflare\'), (b\'access-control-allow-origin\', b\'*\'), (b\'x-request-id\', b\'req_00654453048e4578ab292a9467ba1e1e\'), (b\'openai-processing-ms\', b\'65\'), (b\'openai-version\', b\'2020-10-01\'), (b\'openai-organization\', b\'personal-wjlt5f\'), (b\'openai-project\', b\'proj_563bG7FnxU3biDL35o8XM6he\'), (b\'x-openai-proxy-wasm\', b\'v0.1\'), (b\'cf-cache-status\', b\'DYNAMIC\'), (b\'Access-Control-Expose-Headers\', b\'CF-Ray\'), (b\'Strict-Transport-Security\', b\'max-age=31536000; includeSubDomains; preload\'), (b\'X-Content-Type-Options\', b\'nosniff\'), (b\'Content-Encoding\', b\'br\'), (b\'CF-RAY\', b\'a1c0dc704d73fd29-SIN\'), (b\'alt-svc\', b\'h3=":443"; ma=86400\')])\n2026-07-16 12:02:59,567 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content "HTTP/1.1 404 Not Found"\n2026-07-16 12:02:59,567 | DEBUG | httpcore.http11 | receive_response_body.started request=<Request [b\'GET\']>\n2026-07-16 12:02:59,567 | DEBUG | httpcore.http11 | receive_response_body.complete\n2026-07-16 12:02:59,567 | DEBUG | httpcore.http11 | response_closed.started\n2026-07-16 12:02:59,567 | DEBUG | httpcore.http11 | response_closed.complete\n2026-07-16 12:02:59,567 | DEBUG | openai._base_client | HTTP Response: GET https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content "404 Not Found" Headers({\'date\': \'Thu, 16 Jul 2026 12:02:59 GMT\', \'content-type\': \'application/json\', \'transfer-encoding\': \'chunked\', \'connection\': \'keep-alive\', \'server\': \'cloudflare\', \'access-control-allow-origin\': \'*\', \'x-request-id\': \'req_00654453048e4578ab292a9467ba1e1e\', \'openai-processing-ms\': \'65\', \'openai-version\': \'2020-10-01\', \'openai-organization\': \'personal-wjlt5f\', \'openai-project\': \'proj_563bG7FnxU3biDL35o8XM6he\', \'x-openai-proxy-wasm\': \'v0.1\', \'cf-cache-status\': \'DYNAMIC\', \'access-control-expose-headers\': \'CF-Ray\', \'strict-transport-security\': \'max-age=31536000; includeSubDomains; preload\', \'x-content-type-options\': \'nosniff\', \'content-encoding\': \'br\', \'cf-ray\': \'a1c0dc704d73fd29-SIN\', \'alt-svc\': \'h3=":443"; ma=86400\'})\n2026-07-16 12:02:59,568 | DEBUG | openai._base_client | request_id: req_00654453048e4578ab292a9467ba1e1e\n2026-07-16 12:02:59,568 | DEBUG | openai._base_client | Encountered httpx.HTTPStatusError\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1085, in request\n    response.raise_for_status()\n  File "/usr/local/lib/python3.12/dist-packages/httpx/_models.py", line 829, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error \'404 Not Found\' for url \'https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content\'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404\n2026-07-16 12:02:59,571 | DEBUG | openai._base_client | Not retrying\n2026-07-16 12:02:59,571 | DEBUG | openai._base_client | Re-raising status error\nTraceback (most recent call last):\n  File "<frozen runpy>", line 198, in _run_module_as_main\n  File "<frozen runpy>", line 88, in _run_code\n  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 215, in <module>\n    main()\n  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 211, in main\n    _print_result(command_handlers[args.command]())\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 136, in <lambda>\n    command_handlers[args.command] = lambda: run_teacher_batch(config, args.prepare_only)\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/teacher.py", line 369, in run_teacher_batch\n    raw_text = client.files.content(output_file_id).text\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/dist-packages/openai/resources/files.py", line 316, in content\n    return self._get(\n           ^^^^^^^^^^\n  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1263, in get\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1105, in request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.NotFoundError: Error code: 404 - {\'error\': {\'message\': \'No such File object: file-YSRyMTNErQUrNJ3LpVLVpA\', \'type\': \'invalid_request_error\', \'param\': \'id\', \'code\': None}, \'detail\': {\'message\': \'No such File object: file-YSRyMTNErQUrNJ3LpVLVpA\', \'code\': None}}\n2026-07-16 12:02:59,706 | DEBUG | httpcore.connection | close.started\n2026-07-16 12:02:59,706 | DEBUG | httpcore.connection | close.complete\n')

In [9]:
require_teacher_outputs(FORMAL_CONFIG)

Teacher train rows: 1033
Teacher validation rows: 130

In [6]:
FORMAL_ROOT = output_root_for(FORMAL_CONFIG)
print("Formal root:", FORMAL_ROOT)

cli("prepare-data", "--config", FORMAL_CONFIG)

if not os.getenv("OPENAI_API_KEY"):
    raise RuntimeError("Add OPENAI_API_KEY to Colab Secrets first.")
ensure_teacher_pilot(FORMAL_CONFIG)
cli("teacher-batch", "--config", FORMAL_CONFIG)
require_teacher_outputs(FORMAL_CONFIG)

Formal root: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b

$ /usr/bin/python3 -u -m amazon_review_alignment.cli prepare-data --config configs/rlhf_a100_online_v2.yaml
2026-07-16 11:54:14,648 | INFO | numexpr.utils | NumExpr defaulting to 12 threads.
2026-07-16 11:54:15,122 | INFO | datasets | TensorFlow version 2.20.0 available.
2026-07-16 11:54:15,123 | INFO | datasets | JAX version 0.7.2 available.
2026-07-16 11:54:15,448 | INFO | amazon_review_alignment.data | Streaming reviews from https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl
2026-07-16 11:54:16,199 | INFO | httpx | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
2026-07-16 11:54:16,564 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/datasets/McAuley-Lab/Amazon-Reviews-2023/revision/main "HTTP/1.1 200 OK"
2026-07-16 11:54:16,806 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/datasets/McAuley-Lab/Amazon-Reviews-2023/tree/main/raw%2Freview_categories?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-07-16 11:54:17,150 | INFO | httpx | HTTP Request: GET https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl "HTTP/1.1 302 Found"
2026-07-16 11:54:17,168 | INFO | httpx | HTTP Request: GET https://cas-bridge.xethub.hf.co/xet-bridge-us/65af4645d0a5cc99d51642da/28866377eb7aec134fa8b5028e64a9d5de9960a671ef0babc5e0e177e1a96bc1?Expires=1784206457&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jYXMtYnJpZGdlLnhldGh1Yi5oZi5jby94ZXQtYnJpZGdlLXVzLzY1YWY0NjQ1ZDBhNWNjOTlkNTE2NDJkYS8yODg2NjM3N2ViN2FlYzEzNGZhOGI1MDI4ZTY0YTlkNWRlOTk2MGE2NzFlZjBiYWJjNWUwZTE3N2UxYTk2YmMxKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc4NDIwNjQ1N319fV19&Signature=MEUCIGEtJwD2aAj2ztQQjwnFTgFT441K0FDhBjQXH0YZQSl3AiEAzDARjlxksfvjUEjvIQi1AT9PNriy%7Ed7vvA4CVRnyp6Q_&Key-Pair-Id=K3EPXBYC3CKDRZ&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Electronics.jsonl%3B+filename%3D%22Electronics.jsonl%22%3B&X-Xet-Cas-Uid=69de1b2958833616a2cc4a2f&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=cas%2F20260716%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260716T115417Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=d9fa836508f61d24a5aaa46d1b4c48bd201940634c67670c9e6488618ab05310 "HTTP/1.1 206 Partial Content"
2026-07-16 11:54:19,381 | INFO | httpx | HTTP Request: GET https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl "HTTP/1.1 302 Found"
2026-07-16 11:54:19,389 | INFO | httpx | HTTP Request: GET https://cas-bridge.xethub.hf.co/xet-bridge-us/65af4645d0a5cc99d51642da/28866377eb7aec134fa8b5028e64a9d5de9960a671ef0babc5e0e177e1a96bc1?Expires=1784206459&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jYXMtYnJpZGdlLnhldGh1Yi5oZi5jby94ZXQtYnJpZGdlLXVzLzY1YWY0NjQ1ZDBhNWNjOTlkNTE2NDJkYS8yODg2NjM3N2ViN2FlYzEzNGZhOGI1MDI4ZTY0YTlkNWRlOTk2MGE2NzFlZjBiYWJjNWUwZTE3N2UxYTk2YmMxKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc4NDIwNjQ1OX19fV19&Signature=MEYCIQCLwq0ucDcmxRiCEiLk%7Er4lKuZIJwhruQOZoQAA0zqrhAIhAMFTjVPLiSyvKGBs9MgGISmxlpPDhrEM2N34J1b6ogxY&Key-Pair-Id=K3EPXBYC3CKDRZ&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Electronics.jsonl%3B+filename%3D%22Electronics.jsonl%22%3B&X-Xet-Cas-Uid=69de1b2958833616a2cc4a2f&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=cas%2F20260716%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260716T115419Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=259e78a2a353ca26e064b6989ab118246ca1568a21e6b2ed6983b5bda7479265 "HTTP/1.1 206 Partial Content"
2026-07-16 11:54:21,095 | INFO | httpx | HTTP Request: GET https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl "HTTP/1.1 302 Found"
2026-07-16 11:54:21,607 | INFO | httpx | HTTP Request: GET https://cas-bridge.xethub.hf.co/xet-bridge-us/65af4645d0a5cc99d51642da/28866377eb7aec134fa8b5028e64a9d5de9960a671ef0babc5e0e177e1a96bc1?Expires=1784206460&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jYXMtYnJpZGdlLnhldGh1Yi5oZi5jby94ZXQtYnJpZGdlLXVzLzY1YWY0NjQ1ZDBhNWNjOTlkNTE2NDJkYS8yODg2NjM3N2ViN2FlYzEzNGZhOGI1MDI4ZTY0YTlkNWRlOTk2MGE2NzFlZjBiYWJjNWUwZTE3N2UxYTk2YmMxKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc4NDIwNjQ2MH19fV19&Signature=MEQCICqX9WGvXoHKdGR7QJwFZ%7E-A5xxaIbB55x4uerDcgO9EAiAeepD9jubhf9CtrgZ8JALy6cUZT%7EqHO8lUGCeAcs4E4A__&Key-Pair-Id=K3EPXBYC3CKDRZ&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Electronics.jsonl%3B+filename%3D%22Electronics.jsonl%22%3B&X-Xet-Cas-Uid=69de1b2958833616a2cc4a2f&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=cas%2F20260716%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260716T115420Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=94bfdfcd56d86a84060fbce548bc95a3454814e881da9fdec3b22ec28d45211e "HTTP/1.1 206 Partial Content"
2026-07-16 11:54:39,393 | INFO | httpx | HTTP Request: GET https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl "HTTP/1.1 302 Found"
2026-07-16 11:54:39,857 | INFO | httpx | HTTP Request: GET https://cas-bridge.xethub.hf.co/xet-bridge-us/65af4645d0a5cc99d51642da/28866377eb7aec134fa8b5028e64a9d5de9960a671ef0babc5e0e177e1a96bc1?Expires=1784206479&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jYXMtYnJpZGdlLnhldGh1Yi5oZi5jby94ZXQtYnJpZGdlLXVzLzY1YWY0NjQ1ZDBhNWNjOTlkNTE2NDJkYS8yODg2NjM3N2ViN2FlYzEzNGZhOGI1MDI4ZTY0YTlkNWRlOTk2MGE2NzFlZjBiYWJjNWUwZTE3N2UxYTk2YmMxKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc4NDIwNjQ3OX19fV19&Signature=MEYCIQDoTTHRo-qro2rkqLXknrYVsGjyqQ4zrYg6XGCDqK8UJgIhAI9W2wMzofbxLLEh0BvNhNh9Xl1Y59mUH-KjX-y5s8Vm&Key-Pair-Id=K3EPXBYC3CKDRZ&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27Electronics.jsonl%3B+filename%3D%22Electronics.jsonl%22%3B&X-Xet-Cas-Uid=69de1b2958833616a2cc4a2f&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=cas%2F20260716%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260716T115439Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=49a96b6abdd4611d745ca1dcb42aa2f32dfa76b948c1124a017e7be8f3fb5dac "HTTP/1.1 206 Partial Content"
2026-07-16 11:55:02,815 | INFO | amazon_review_alignment.data | Prepared 5000 reviews under /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/data
{
  "source_url": "https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Electronics.jsonl",
  "scanned_reviews": 29280,
  "selected_reviews": 5000,
  "selection_policy": "unique normalized text and at most one review per parent_asin",
  "rating_counts": {
    "1": 1000,
    "2": 1000,
    "3": 1000,
    "4": 1000,
    "5": 1000
  },
  "split_sizes": {
    "train": 3500,
    "validation": 500,
    "test": 1000
  },
  "split_rating_counts": {
    "train": {
      "1": 700,
      "2": 700,
      "3": 700,
      "4": 700,
      "5": 700
    },
    "validation": {
      "1": 100,
      "2": 100,
      "3": 100,
      "4": 100,
      "5": 100
    },
    "test": {
      "1": 200,
      "2": 200,
      "3": 200,
      "4": 200,
      "5": 200
    }
  }
}
Reusing teacher pilot summary: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/teacher/pilot_summary.json

$ /usr/bin/python3 -u -m amazon_review_alignment.cli teacher-batch --config configs/rlhf_a100_online_v2.yaml
2026-07-16 11:55:10,874 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/batches/batch_6a2f615a5d4c81908c06a49ef4bae222 "HTTP/1.1 200 OK"
2026-07-16 11:55:11,710 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content "HTTP/1.1 404 Not Found"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 215, in <module>
    main()
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 211, in main
    _print_result(command_handlers[args.command]())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 136, in <lambda>
    command_handlers[args.command] = lambda: run_teacher_batch(config, args.prepare_only)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/teacher.py", line 369, in run_teacher_batch
    raw_text = client.files.content(output_file_id).text
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/resources/files.py", line 316, in content
    return self._get(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1263, in get
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1105, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'No such File object: file-YSRyMTNErQUrNJ3LpVLVpA', 'type': 'invalid_request_error', 'param': 'id', 'code': None}, 'detail': {'message': 'No such File object: file-YSRyMTNErQUrNJ3LpVLVpA', 'code': None}}

===== LAST 200 LINES =====
2026-07-16 11:55:10,874 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/batches/batch_6a2f615a5d4c81908c06a49ef4bae222 "HTTP/1.1 200 OK"
2026-07-16 11:55:11,710 | INFO | httpx | HTTP Request: GET https://api.openai.com/v1/files/file-YSRyMTNErQUrNJ3LpVLVpA/content "HTTP/1.1 404 Not Found"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 215, in <module>
    main()
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 211, in main
    _print_result(command_handlers[args.command]())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/cli.py", line 136, in <lambda>
    command_handlers[args.command] = lambda: run_teacher_batch(config, args.prepare_only)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/amazon-review-alignment-workspace/repo/src/amazon_review_alignment/teacher.py", line 369, in run_teacher_batch
    raw_text = client.files.content(output_file_id).text
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/resources/files.py", line 316, in content
    return self._get(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1263, in get
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1105, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'No such File object: file-YSRyMTNErQUrNJ3LpVLVpA', 'type': 'invalid_request_error', 'param': 'id', 'code': None}, 'detail': {'message': 'No such File object: file-YSRyMTNErQUrNJ3LpVLVpA', 'code': None}}

RuntimeError: Command failed with exit code 1: /usr/bin/python3 -u -m amazon_review_alignment.cli teacher-batch --config configs/rlhf_a100_online_v2.yaml

In [11]:
from amazon_review_alignment.utils import read_jsonl

root = output_root_for(FORMAL_CONFIG)

train = {row["id"] for row in read_jsonl(root / "data" / "train.jsonl")}
val = {row["id"] for row in read_jsonl(root / "data" / "validation.jsonl")}

pref_train = read_jsonl(root / "teacher" / "preferences_train.jsonl")
pref_val = read_jsonl(root / "teacher" / "preferences_validation.jsonl")

print("train prefs:", len(pref_train))
print("val prefs:", len(pref_val))

print("train ids all in current train split:", all(row["id"] in train for row in pref_train))
print("val ids all in current validation split:", all(row["id"] in val for row in pref_val))

print("train overlap:", sum(row["id"] in train for row in pref_train), "/", len(pref_train))
print("val overlap:", sum(row["id"] in val for row in pref_val), "/", len(pref_val))

print("teacher models:", sorted({row.get("teacher_model") for row in pref_train + pref_val}))

train prefs: 1033
val prefs: 130
train ids all in current train split: True
val ids all in current validation split: True
train overlap: 1033 / 1033
val overlap: 130 / 130
teacher models: ['gpt-5.4-mini-2026-03-17']

In [13]:
root = output_root_for(FORMAL_CONFIG)

paths = {
    "sft": root / "models" / "sft",
    "sft_merged": root / "models" / "sft-merged",
    "dpo": root / "models" / "dpo-v2",
    "ppo": root / "models" / "ppo-v2",
    "grpo": root / "models" / "grpo-v2",
    "test": root / "data" / "test.jsonl",
}

for name, path in paths.items():
    print(name, path, path.exists())

sft /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/models/sft True
sft_merged /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/models/sft-merged True
dpo /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/models/dpo-v2 True
ppo /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/models/ppo-v2 True
grpo /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/models/grpo-v2 True
test /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/data/test.jsonl True

## 8. Formal Training: Stage-By-Stage

Run these cells in order. They are split deliberately so a Colab disconnect or a late-stage failure does not force you to rerun earlier training stages.

### 8.1 SFT Adapter

In [12]:
cli("train-sft", "--config", FORMAL_CONFIG)

$ /usr/bin/python3 -u -m amazon_review_alignment.cli train-sft --config configs/rlhf_a100_online_v2.yaml
2026-07-16 12:08:27,812 | INFO | numexpr.utils | NumExpr defaulting to 12 threads.
2026-07-16 12:08:28,279 | INFO | datasets | TensorFlow version 2.20.0 available.
2026-07-16 12:08:28,281 | INFO | datasets | JAX version 0.7.2 available.
2026-07-16 12:08:38,036 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:08:38,041 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 12:08:38,294 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:08:38,300 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 12:08:38,566 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:08:38,572 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 12:08:38,811 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-16 12:08:39,056 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-16 12:08:40,916 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B "HTTP/1.1 200 OK"
2026-07-16 12:08:41,442 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:08:41,448 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 12:08:41,724 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:08:41,731 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 12:08:44,252 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-07-16 12:08:44,510 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors.index.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:08:44,516 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/model.safetensors.index.json "HTTP/1.1 200 OK"
2026-07-16 12:08:44,763 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors-00001-of-00001.safetensors "HTTP/1.1 302 Found"
The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

Loading weights:   0%|          | 0/320 [00:00<?, ?it/s]
Loading weights:   0%|          | 1/320 [00:00<01:24,  3.77it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Loading weights:   8%|▊         | 25/320 [00:00<00:03, 85.79it/s]
Loading weights:  17%|█▋        | 53/320 [00:00<00:01, 147.89it/s]
Loading weights:  29%|██▉       | 93/320 [00:00<00:01, 226.06it/s]
Loading weights:  40%|████      | 128/320 [00:00<00:00, 264.41it/s]
Loading weights:  50%|████▉     | 159/320 [00:00<00:00, 273.60it/s]
Loading weights:  62%|██████▎   | 200/320 [00:00<00:00, 308.26it/s]
Loading weights:  74%|███████▍  | 238/320 [00:00<00:00, 328.40it/s]
Loading weights:  86%|████████▋ | 276/320 [00:01<00:00, 343.28it/s]
Loading weights:  98%|█████████▊| 312/320 [00:01<00:00, 329.36it/s]
Loading weights: 100%|██████████| 320/320 [00:01<00:00, 262.19it/s]
2026-07-16 12:08:46,798 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/generation_config.json "HTTP/1.1 404 Not Found"
2026-07-16 12:08:47,035 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:08:47,041 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 12:08:47,285 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Adding EOS to train dataset:   0%|          | 0/1033 [00:00<?, ? examples/s]
Adding EOS to train dataset: 100%|██████████| 1033/1033 [00:00<00:00, 24827.90 examples/s]

Tokenizing train dataset:   0%|          | 0/1033 [00:00<?, ? examples/s]
Tokenizing train dataset:   6%|▌         | 59/1033 [00:00<00:01, 574.79 examples/s]
Tokenizing train dataset:  11%|█▏        | 118/1033 [00:00<00:01, 577.09 examples/s]
Tokenizing train dataset:  19%|█▉        | 200/1033 [00:00<00:01, 550.57 examples/s]
Tokenizing train dataset:  25%|██▌       | 260/1033 [00:00<00:01, 557.84 examples/s]
Tokenizing train dataset:  31%|███▏      | 324/1033 [00:00<00:01, 582.04 examples/s]
Tokenizing train dataset:  40%|███▉      | 409/1033 [00:00<00:01, 565.20 examples/s]
Tokenizing train dataset:  46%|████▌     | 474/1033 [00:00<00:00, 585.75 examples/s]
Tokenizing train dataset:  54%|█████▍    | 559/1033 [00:00<00:00, 572.75 examples/s]
Tokenizing train dataset:  60%|█████▉    | 619/1033 [00:01<00:00, 573.78 examples/s]
Tokenizing train dataset:  66%|██████▌   | 682/1033 [00:01<00:00, 585.66 examples/s]
Tokenizing train dataset:  74%|███████▍  | 766/1033 [00:01<00:00, 573.09 examples/s]
Tokenizing train dataset:  82%|████████▏ | 846/1033 [00:01<00:00, 553.93 examples/s]
Tokenizing train dataset:  90%|████████▉ | 929/1033 [00:01<00:00, 548.73 examples/s]
Tokenizing train dataset:  97%|█████████▋| 1000/1033 [00:01<00:00, 424.94 examples/s]
Tokenizing train dataset: 100%|██████████| 1033/1033 [00:01<00:00, 522.87 examples/s]

Adding EOS to eval dataset:   0%|          | 0/130 [00:00<?, ? examples/s]
Adding EOS to eval dataset: 100%|██████████| 130/130 [00:00<00:00, 17532.46 examples/s]

Tokenizing eval dataset:   0%|          | 0/130 [00:00<?, ? examples/s]
Tokenizing eval dataset:  46%|████▌     | 60/130 [00:00<00:00, 591.52 examples/s]
Tokenizing eval dataset: 100%|██████████| 130/130 [00:00<00:00, 520.02 examples/s]
Tokenizing eval dataset: 100%|██████████| 130/130 [00:00<00:00, 525.93 examples/s]
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 248046, 'pad_token_id': 248044}.

  0%|          | 0/65 [00:00<?, ?it/s]2026-07-16 12:08:51,700 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/telemetry/trl/SFTTrainer "HTTP/1.1 200 OK"

  2%|▏         | 1/65 [00:08<08:42,  8.16s/it]

KeyboardInterrupt:

### 8.2 Merge SFT Adapter

In [ ]:
cli("merge-sft", "--config", FORMAL_CONFIG)

### 8.3 DPO v2 Adapter

In [ ]:
cli("train-dpo", "--config", FORMAL_CONFIG)

### 8.4 Build Reward/PPO/GRPO Data

In [ ]:
cli("build-rlhf-data", "--config", FORMAL_CONFIG)

manifest_path = FORMAL_ROOT / "rlhf" / "data_manifest.json"
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
print(json.dumps(manifest, indent=2))
assert manifest["ppo_grpo_shared_prompt_ids"] is True

### 8.5 Reward Model

In [ ]:
cli("train-reward", "--config", FORMAL_CONFIG)

### 8.6 PPO v2 Adapter

In [ ]:
cli("train-ppo", "--config", FORMAL_CONFIG)

### 8.7 GRPO v2 Adapter

In [ ]:
cli("train-grpo", "--config", FORMAL_CONFIG)

## 9. Evaluate The Five Trained Models

In [14]:
TRAINED_VARIANTS = ["base", "sft", "dpo", "ppo", "grpo"]
cli("evaluate", "--config", FORMAL_CONFIG, "--variants", *TRAINED_VARIANTS, "--force-inference")
cli("build-report", "--config", FORMAL_CONFIG)

display(pd.read_csv(FORMAL_ROOT / "evaluation" / "metrics.csv"))
print("Report:", FORMAL_ROOT / "evaluation" / "report.md")

$ /usr/bin/python3 -u -m amazon_review_alignment.cli evaluate --config configs/rlhf_a100_online_v2.yaml --variants base sft dpo ppo grpo --force-inference
2026-07-16 12:09:50,074 | INFO | numexpr.utils | NumExpr defaulting to 12 threads.
2026-07-16 12:09:56,868 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:09:56,874 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 12:09:57,134 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:09:57,140 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 12:09:57,375 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:09:57,381 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 12:09:57,619 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-16 12:09:57,856 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-16 12:09:59,745 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B "HTTP/1.1 200 OK"
2026-07-16 12:10:00,101 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:10:00,108 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 12:10:00,644 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:10:00,651 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 12:10:03,581 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-07-16 12:10:03,820 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors.index.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:10:03,826 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/model.safetensors.index.json "HTTP/1.1 200 OK"
2026-07-16 12:10:04,079 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors-00001-of-00001.safetensors "HTTP/1.1 302 Found"
The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

Loading weights:   0%|          | 0/320 [00:00<?, ?it/s]
Loading weights:   0%|          | 1/320 [00:00<01:21,  3.90it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Loading weights:   8%|▊         | 27/320 [00:00<00:03, 95.43it/s]
Loading weights:  20%|██        | 65/320 [00:00<00:01, 190.11it/s]
Loading weights:  31%|███       | 99/320 [00:00<00:00, 234.90it/s]
Loading weights:  44%|████▍     | 142/320 [00:00<00:00, 292.97it/s]
Loading weights:  55%|█████▌    | 176/320 [00:00<00:00, 307.25it/s]
Loading weights:  66%|██████▌   | 210/320 [00:00<00:00, 315.54it/s]
Loading weights:  79%|███████▉  | 252/320 [00:00<00:00, 342.40it/s]
Loading weights:  91%|█████████ | 290/320 [00:01<00:00, 352.52it/s]
Loading weights: 100%|██████████| 320/320 [00:01<00:00, 273.92it/s]
2026-07-16 12:10:06,017 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/generation_config.json "HTTP/1.1 404 Not Found"
2026-07-16 12:10:06,255 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 12:10:06,261 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 12:10:06,499 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
2026-07-16 12:12:41,015 | INFO | amazon_review_alignment.inference | base inference: 25/500
2026-07-16 12:15:15,134 | INFO | amazon_review_alignment.inference | base inference: 50/500
2026-07-16 12:18:00,699 | INFO | amazon_review_alignment.inference | base inference: 75/500
2026-07-16 12:20:43,730 | INFO | amazon_review_alignment.inference | base inference: 100/500
2026-07-16 12:23:25,231 | INFO | amazon_review_alignment.inference | base inference: 125/500
2026-07-16 12:26:01,286 | INFO | amazon_review_alignment.inference | base inference: 150/500
2026-07-16 12:28:48,665 | INFO | amazon_review_alignment.inference | base inference: 175/500
2026-07-16 12:31:47,179 | INFO | amazon_review_alignment.inference | base inference: 200/500
2026-07-16 12:34:40,033 | INFO | amazon_review_alignment.inference | base inference: 225/500
2026-07-16 12:37:30,160 | INFO | amazon_review_alignment.inference | base inference: 250/500
2026-07-16 12:40:19,329 | INFO | amazon_review_alignment.inference | base inference: 275/500
2026-07-16 12:43:05,042 | INFO | amazon_review_alignment.inference | base inference: 300/500
2026-07-16 12:45:58,652 | INFO | amazon_review_alignment.inference | base inference: 325/500
2026-07-16 12:48:47,353 | INFO | amazon_review_alignment.inference | base inference: 350/500
2026-07-16 12:51:24,172 | INFO | amazon_review_alignment.inference | base inference: 375/500
2026-07-16 12:54:06,445 | INFO | amazon_review_alignment.inference | base inference: 400/500
2026-07-16 12:56:49,086 | INFO | amazon_review_alignment.inference | base inference: 425/500
2026-07-16 12:59:38,738 | INFO | amazon_review_alignment.inference | base inference: 450/500
2026-07-16 13:02:18,936 | INFO | amazon_review_alignment.inference | base inference: 475/500
2026-07-16 13:05:11,430 | INFO | amazon_review_alignment.inference | base inference: 500/500
2026-07-16 13:05:14,178 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 13:05:14,185 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 13:05:14,446 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 13:05:14,454 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 13:05:14,719 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 13:05:14,726 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 13:05:14,966 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-16 13:05:15,202 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-16 13:05:17,232 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B "HTTP/1.1 200 OK"
2026-07-16 13:05:17,559 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 13:05:17,568 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 13:05:17,821 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 13:05:17,828 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 13:05:18,066 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-07-16 13:05:18,309 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors.index.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 13:05:18,315 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/model.safetensors.index.json "HTTP/1.1 200 OK"
2026-07-16 13:05:18,553 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors-00001-of-00001.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/320 [00:00<?, ?it/s]
Loading weights:   0%|          | 1/320 [00:00<01:22,  3.85it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Loading weights:  12%|█▎        | 40/320 [00:00<00:02, 139.97it/s]
Loading weights:  24%|██▍       | 76/320 [00:00<00:01, 211.60it/s]
Loading weights:  35%|███▌      | 113/320 [00:00<00:00, 262.08it/s]
Loading weights:  46%|████▌     | 147/320 [00:00<00:00, 280.59it/s]
Loading weights:  58%|█████▊    | 185/320 [00:00<00:00, 306.63it/s]
Loading weights:  70%|██████▉   | 223/320 [00:00<00:00, 326.31it/s]
Loading weights:  81%|████████  | 258/320 [00:00<00:00, 320.80it/s]
Loading weights:  94%|█████████▍| 301/320 [00:01<00:00, 346.64it/s]
Loading weights: 100%|██████████| 320/320 [00:01<00:00, 275.59it/s]
2026-07-16 13:05:20,210 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/generation_config.json "HTTP/1.1 404 Not Found"
2026-07-16 13:05:20,492 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 13:05:20,537 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 13:05:20,774 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
2026-07-16 13:08:20,536 | INFO | amazon_review_alignment.inference | sft inference: 25/500
2026-07-16 13:11:24,722 | INFO | amazon_review_alignment.inference | sft inference: 50/500
2026-07-16 13:14:24,678 | INFO | amazon_review_alignment.inference | sft inference: 75/500
2026-07-16 13:17:34,645 | INFO | amazon_review_alignment.inference | sft inference: 100/500
2026-07-16 13:20:48,884 | INFO | amazon_review_alignment.inference | sft inference: 125/500
2026-07-16 13:23:44,783 | INFO | amazon_review_alignment.inference | sft inference: 150/500
2026-07-16 13:26:39,909 | INFO | amazon_review_alignment.inference | sft inference: 175/500
2026-07-16 13:29:56,861 | INFO | amazon_review_alignment.inference | sft inference: 200/500
2026-07-16 13:33:00,702 | INFO | amazon_review_alignment.inference | sft inference: 225/500
2026-07-16 13:36:02,640 | INFO | amazon_review_alignment.inference | sft inference: 250/500
2026-07-16 13:38:59,721 | INFO | amazon_review_alignment.inference | sft inference: 275/500
2026-07-16 13:42:04,657 | INFO | amazon_review_alignment.inference | sft inference: 300/500
2026-07-16 13:45:11,159 | INFO | amazon_review_alignment.inference | sft inference: 325/500
2026-07-16 13:48:05,242 | INFO | amazon_review_alignment.inference | sft inference: 350/500
2026-07-16 13:51:06,500 | INFO | amazon_review_alignment.inference | sft inference: 375/500
2026-07-16 13:53:48,004 | INFO | amazon_review_alignment.inference | sft inference: 400/500
2026-07-16 13:56:40,383 | INFO | amazon_review_alignment.inference | sft inference: 425/500
2026-07-16 13:59:51,918 | INFO | amazon_review_alignment.inference | sft inference: 450/500
2026-07-16 14:02:50,969 | INFO | amazon_review_alignment.inference | sft inference: 475/500
2026-07-16 14:05:54,587 | INFO | amazon_review_alignment.inference | sft inference: 500/500

Loading weights:   0%|          | 0/320 [00:00<?, ?it/s]
Loading weights:   0%|          | 1/320 [00:32<2:50:30, 32.07s/it]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Loading weights:   2%|▎         | 8/320 [00:32<15:27,  2.97s/it]
Loading weights:   3%|▎         | 10/320 [00:32<11:26,  2.21s/it]
Loading weights:   4%|▍         | 12/320 [00:35<09:49,  1.91s/it]
Loading weights:   7%|▋         | 23/320 [00:35<03:06,  1.59it/s]
Loading weights:   8%|▊         | 26/320 [00:36<02:37,  1.87it/s]
Loading weights:   9%|▉         | 28/320 [00:40<03:47,  1.28it/s]
Loading weights:   9%|▉         | 30/320 [00:41<03:52,  1.25it/s]
Loading weights:  11%|█▏        | 36/320 [00:42<02:24,  1.96it/s]
Loading weights:  12%|█▏        | 39/320 [00:43<01:57,  2.39it/s]
Loading weights:  12%|█▎        | 40/320 [00:43<01:59,  2.34it/s]
Loading weights:  13%|█▎        | 41/320 [00:44<02:09,  2.16it/s]
Loading weights:  13%|█▎        | 42/320 [00:45<02:19,  1.99it/s]
Loading weights:  14%|█▍        | 44/320 [00:46<02:40,  1.72it/s]
Loading weights:  14%|█▍        | 45/320 [00:47<02:26,  1.88it/s]
Loading weights:  14%|█▍        | 46/320 [00:47<02:08,  2.14it/s]
Loading weights:  15%|█▍        | 47/320 [00:47<01:50,  2.48it/s]
Loading weights:  17%|█▋        | 53/320 [00:47<00:42,  6.27it/s]
Loading weights:  19%|█▉        | 61/320 [00:47<00:23, 11.16it/s]
Loading weights:  20%|█▉        | 63/320 [00:49<00:47,  5.45it/s]
Loading weights:  25%|██▍       | 79/320 [00:50<00:29,  8.08it/s]
Loading weights:  25%|██▌       | 81/320 [00:51<00:31,  7.57it/s]
Loading weights:  28%|██▊       | 89/320 [00:51<00:21, 10.86it/s]
Loading weights:  29%|██▉       | 92/320 [00:51<00:19, 11.97it/s]
Loading weights:  30%|██▉       | 95/320 [00:52<00:35,  6.29it/s]
Loading weights:  31%|███       | 99/320 [00:53<00:32,  6.73it/s]
Loading weights:  32%|███▏      | 101/320 [00:53<00:34,  6.31it/s]
Loading weights:  32%|███▎      | 104/320 [00:55<00:59,  3.64it/s]
Loading weights:  33%|███▎      | 106/320 [00:55<00:50,  4.27it/s]
Loading weights:  36%|███▌      | 114/320 [00:56<00:28,  7.30it/s]
Loading weights:  36%|███▋      | 116/320 [00:56<00:26,  7.84it/s]
Loading weights:  37%|███▋      | 118/320 [00:57<00:36,  5.57it/s]
Loading weights:  37%|███▋      | 119/320 [00:57<00:40,  4.94it/s]
Loading weights:  38%|███▊      | 120/320 [00:57<00:48,  4.15it/s]
Loading weights:  40%|████      | 128/320 [00:58<00:25,  7.62it/s]
Loading weights:  40%|████      | 129/320 [00:58<00:24,  7.66it/s]
Loading weights:  41%|████      | 131/320 [00:58<00:23,  8.18it/s]
Loading weights:  41%|████▏     | 132/320 [00:59<00:44,  4.26it/s]
Loading weights:  42%|████▏     | 133/320 [01:00<00:53,  3.47it/s]
Loading weights:  42%|████▏     | 134/320 [01:00<00:57,  3.21it/s]
Loading weights:  47%|████▋     | 151/320 [01:00<00:10, 16.42it/s]
Loading weights:  52%|█████▏    | 167/320 [01:03<00:15,  9.72it/s]
Loading weights:  53%|█████▎    | 171/320 [01:04<00:18,  7.89it/s]
Loading weights:  54%|█████▍    | 174/320 [01:05<00:23,  6.21it/s]
Loading weights:  57%|█████▋    | 181/320 [01:07<00:33,  4.19it/s]
Loading weights:  58%|█████▊    | 186/320 [01:08<00:26,  5.07it/s]
Loading weights:  59%|█████▉    | 188/320 [01:09<00:30,  4.27it/s]
Loading weights:  61%|██████    | 195/320 [01:09<00:21,  5.93it/s]
Loading weights:  62%|██████▏   | 198/320 [01:12<00:36,  3.32it/s]
Loading weights:  63%|██████▎   | 201/320 [01:12<00:32,  3.64it/s]
Loading weights:  64%|██████▍   | 204/320 [01:13<00:30,  3.74it/s]
Loading weights:  64%|██████▍   | 205/320 [01:13<00:32,  3.56it/s]
Loading weights:  64%|██████▍   | 206/320 [01:15<00:50,  2.27it/s]
Loading weights:  69%|██████▉   | 220/320 [01:15<00:13,  7.18it/s]
Loading weights:  69%|██████▉   | 222/320 [01:16<00:15,  6.51it/s]
Loading weights:  70%|███████   | 224/320 [01:17<00:17,  5.44it/s]
Loading weights:  71%|███████   | 226/320 [01:18<00:30,  3.11it/s]
Loading weights:  74%|███████▍  | 238/320 [01:19<00:11,  6.99it/s]
Loading weights:  75%|███████▌  | 240/320 [01:21<00:20,  3.86it/s]
Loading weights:  78%|███████▊  | 248/320 [01:21<00:11,  6.07it/s]
Loading weights:  78%|███████▊  | 250/320 [01:21<00:11,  6.35it/s]
Loading weights:  79%|███████▉  | 252/320 [01:22<00:11,  5.90it/s]
Loading weights:  79%|███████▉  | 254/320 [01:24<00:23,  2.83it/s]
Loading weights:  81%|████████  | 259/320 [01:25<00:14,  4.09it/s]
Loading weights:  83%|████████▎ | 265/320 [01:25<00:09,  5.94it/s]
Loading weights:  90%|█████████ | 288/320 [01:27<00:03,  9.71it/s]
Loading weights:  91%|█████████ | 290/320 [01:27<00:03,  9.94it/s]
Loading weights:  91%|█████████▏| 292/320 [01:27<00:03,  8.64it/s]
Loading weights:  92%|█████████▏| 294/320 [01:28<00:03,  8.50it/s]
Loading weights:  94%|█████████▍| 301/320 [01:28<00:01, 12.19it/s]
Loading weights:  95%|█████████▌| 305/320 [01:29<00:02,  6.35it/s]
Loading weights:  98%|█████████▊| 312/320 [01:31<00:01,  5.79it/s]
Loading weights: 100%|██████████| 320/320 [01:31<00:00,  3.51it/s]
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
2026-07-16 14:11:05,077 | INFO | amazon_review_alignment.inference | dpo inference: 25/500
2026-07-16 14:14:17,276 | INFO | amazon_review_alignment.inference | dpo inference: 50/500
2026-07-16 14:17:37,099 | INFO | amazon_review_alignment.inference | dpo inference: 75/500
2026-07-16 14:21:08,716 | INFO | amazon_review_alignment.inference | dpo inference: 100/500
2026-07-16 14:24:50,782 | INFO | amazon_review_alignment.inference | dpo inference: 125/500

,variant,examples,schema_valid_rate,evidence_grounded_rate,word_limit_ok_rate,instruction_following_rate
0,base,500,0.954,0.842,0.954,0.842
1,sft,500,1.000,0.960,1.000,0.960
2,dpo,500,0.846,0.800,0.846,0.800
3,ppo,500,1.000,0.952,1.000,0.952
4,grpo,500,1.000,0.948,1.000,0.948

Report: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/report.md

## 10. Baseline Inference And Unified Evaluation

By default this runs the local Qwen few-shot and nlptown template baselines. If `DEEPSEEK_API_KEY` is configured, it also runs the DeepSeek few-shot baseline.

In [15]:
BASELINE_VARIANTS = [
    "qwen35_2b_fewshot",
    "nlptown_template",
]
if os.getenv("DEEPSEEK_API_KEY"):
    BASELINE_VARIANTS.append("deepseek_v4_pro_fewshot")
else:
    print("Skipping deepseek_v4_pro_fewshot because DEEPSEEK_API_KEY is not set.")
for variant in BASELINE_VARIANTS:
    cli("inference", "--config", FORMAL_CONFIG, "--variant", variant)

ALL_EVAL_VARIANTS = [*TRAINED_VARIANTS, *BASELINE_VARIANTS]
cli("evaluate", "--config", FORMAL_CONFIG, "--variants", *ALL_EVAL_VARIANTS)
cli("build-report", "--config", FORMAL_CONFIG)

metrics = pd.read_csv(FORMAL_ROOT / "evaluation" / "metrics.csv")
display(metrics)
print("Variants evaluated:", ", ".join(ALL_EVAL_VARIANTS))
print("Report:", FORMAL_ROOT / "evaluation" / "report.md")

$ /usr/bin/python3 -u -m amazon_review_alignment.cli inference --config configs/rlhf_a100_online_v2.yaml --variant qwen35_2b_fewshot
2026-07-16 16:55:27,253 | INFO | numexpr.utils | NumExpr defaulting to 12 threads.
2026-07-16 16:55:28,065 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 16:55:28,071 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 16:55:28,337 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 16:55:28,343 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 16:55:28,573 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 16:55:28,579 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 16:55:28,814 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-16 16:55:29,054 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-16 16:55:31,071 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Qwen/Qwen3.5-2B "HTTP/1.1 200 OK"
2026-07-16 16:55:31,419 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 16:55:31,424 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 16:55:31,993 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 16:55:31,999 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 16:55:34,784 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
2026-07-16 16:55:35,020 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors.index.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 16:55:35,026 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/model.safetensors.index.json "HTTP/1.1 200 OK"
2026-07-16 16:55:35,269 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/model.safetensors-00001-of-00001.safetensors "HTTP/1.1 302 Found"
The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

Loading weights:   0%|          | 0/320 [00:00<?, ?it/s]
Loading weights:   0%|          | 1/320 [00:00<01:22,  3.85it/s]/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Loading weights:   8%|▊         | 27/320 [00:00<00:03, 93.98it/s]
Loading weights:  20%|██        | 65/320 [00:00<00:01, 185.64it/s]
Loading weights:  31%|███       | 98/320 [00:00<00:00, 230.51it/s]
Loading weights:  42%|████▏     | 134/320 [00:00<00:00, 268.65it/s]
Loading weights:  54%|█████▍    | 172/320 [00:00<00:00, 297.45it/s]
Loading weights:  64%|██████▍   | 206/320 [00:00<00:00, 304.13it/s]
Loading weights:  78%|███████▊  | 249/320 [00:00<00:00, 341.17it/s]
Loading weights:  89%|████████▉ | 286/320 [00:01<00:00, 349.40it/s]
Loading weights: 100%|██████████| 320/320 [00:01<00:00, 267.72it/s]
2026-07-16 16:55:37,227 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/generation_config.json "HTTP/1.1 404 Not Found"
2026-07-16 16:55:37,467 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 16:55:37,471 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/Qwen/Qwen3.5-2B/15852e8c16360a2fea060d615a32b45270f8a8fc/config.json "HTTP/1.1 200 OK"
2026-07-16 16:55:37,709 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/Qwen/Qwen3.5-2B/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
2026-07-16 16:57:29,079 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 25/500
2026-07-16 16:59:22,927 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 50/500
2026-07-16 17:01:19,900 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 75/500
2026-07-16 17:03:15,933 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 100/500
2026-07-16 17:05:13,464 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 125/500
2026-07-16 17:07:04,595 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 150/500
2026-07-16 17:08:56,952 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 175/500
2026-07-16 17:11:01,644 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 200/500
2026-07-16 17:13:01,663 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 225/500
2026-07-16 17:15:00,578 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 250/500
2026-07-16 17:16:58,544 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 275/500
2026-07-16 17:18:55,460 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 300/500
2026-07-16 17:20:55,198 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 325/500
2026-07-16 17:22:50,963 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 350/500
2026-07-16 17:24:46,863 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 375/500
2026-07-16 17:26:39,678 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 400/500
2026-07-16 17:28:32,245 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 425/500
2026-07-16 17:30:34,787 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 450/500
2026-07-16 17:32:29,379 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 475/500
2026-07-16 17:34:26,794 | INFO | amazon_review_alignment.baselines | qwen35_2b_fewshot baseline inference: 500/500
/content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/qwen35_2b_fewshot.jsonl

$ /usr/bin/python3 -u -m amazon_review_alignment.cli inference --config configs/rlhf_a100_online_v2.yaml --variant nlptown_template
2026-07-16 17:34:35,076 | INFO | numexpr.utils | NumExpr defaulting to 12 threads.
2026-07-16 17:34:35,655 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 17:34:35,904 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/nlptown/bert-base-multilingual-uncased-sentiment/8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d/config.json "HTTP/1.1 200 OK"
2026-07-16 17:34:36,154 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/nlptown/bert-base-multilingual-uncased-sentiment/8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d/config.json "HTTP/1.1 200 OK"
2026-07-16 17:34:36,387 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-07-16 17:34:36,643 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 17:34:36,652 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/nlptown/bert-base-multilingual-uncased-sentiment/8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d/config.json "HTTP/1.1 200 OK"
2026-07-16 17:34:36,922 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 5121.90it/s]
2026-07-16 17:34:42,592 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 17:34:42,825 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/nlptown/bert-base-multilingual-uncased-sentiment/8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 17:34:43,068 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/nlptown/bert-base-multilingual-uncased-sentiment/8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d/tokenizer_config.json "HTTP/1.1 200 OK"
2026-07-16 17:34:43,307 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/nlptown/bert-base-multilingual-uncased-sentiment/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-07-16 17:34:43,539 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/nlptown/bert-base-multilingual-uncased-sentiment/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-07-16 17:34:43,779 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/vocab.txt "HTTP/1.1 307 Temporary Redirect"
2026-07-16 17:34:44,015 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/nlptown/bert-base-multilingual-uncased-sentiment/8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d/vocab.txt "HTTP/1.1 200 OK"
2026-07-16 17:34:44,266 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/nlptown/bert-base-multilingual-uncased-sentiment/8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d/vocab.txt "HTTP/1.1 200 OK"
2026-07-16 17:34:44,598 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/tokenizer.json "HTTP/1.1 404 Not Found"
2026-07-16 17:34:44,845 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
2026-07-16 17:34:45,093 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"
2026-07-16 17:34:45,349 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/nlptown/bert-base-multilingual-uncased-sentiment/8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d/special_tokens_map.json "HTTP/1.1 200 OK"
2026-07-16 17:34:45,588 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/nlptown/bert-base-multilingual-uncased-sentiment/8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d/special_tokens_map.json "HTTP/1.1 200 OK"
2026-07-16 17:34:45,825 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
2026-07-16 17:34:46,132 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/nlptown/bert-base-multilingual-uncased-sentiment "HTTP/1.1 200 OK"
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
2026-07-16 17:34:47,204 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 25/500
2026-07-16 17:34:47,518 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 50/500
2026-07-16 17:34:47,829 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 75/500
2026-07-16 17:34:48,156 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 100/500
2026-07-16 17:34:48,491 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 125/500
2026-07-16 17:34:48,825 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 150/500
2026-07-16 17:34:49,150 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 175/500
2026-07-16 17:34:49,505 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 200/500
2026-07-16 17:34:49,831 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 225/500
2026-07-16 17:34:50,182 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 250/500
2026-07-16 17:34:50,522 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 275/500
2026-07-16 17:34:50,863 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 300/500
2026-07-16 17:34:51,190 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 325/500
2026-07-16 17:34:51,486 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 350/500
2026-07-16 17:34:51,800 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 375/500
2026-07-16 17:34:52,099 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 400/500
2026-07-16 17:34:52,435 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 425/500
2026-07-16 17:34:52,736 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 450/500
2026-07-16 17:34:53,066 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 475/500
2026-07-16 17:34:53,380 | INFO | amazon_review_alignment.baselines | nlptown_template baseline inference: 500/500
/content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/nlptown_template.jsonl

$ /usr/bin/python3 -u -m amazon_review_alignment.cli inference --config configs/rlhf_a100_online_v2.yaml --variant deepseek_v4_pro_fewshot
2026-07-16 17:34:56,823 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:34:58,575 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:01,126 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:02,427 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:03,552 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:05,172 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:06,585 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:07,988 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:09,800 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:11,788 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:13,261 | INFO | amazon_review_alignment.baselines | deepseek_v4_pro_fewshot baseline inference: 10/500
2026-07-16 17:35:13,426 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:14,632 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:15,866 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:18,455 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:20,377 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:21,546 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:23,098 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:24,989 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:26,672 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:28,462 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:29,974 | INFO | amazon_review_alignment.baselines | deepseek_v4_pro_fewshot baseline inference: 20/500
2026-07-16 17:35:30,133 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:32,100 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:33,234 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:35,467 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:36,967 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:39,048 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:40,418 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:42,454 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:44,250 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:45,703 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:47,120 | INFO | amazon_review_alignment.baselines | deepseek_v4_pro_fewshot baseline inference: 30/500
2026-07-16 17:35:47,279 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:49,060 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:51,040 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:52,915 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"
2026-07-16 17:35:54,065 | INFO | httpx | HTTP Request: POST https://api.deepseek.com/chat/completions "HTTP/1.1 200 OK"

,variant,examples,schema_valid_rate,evidence_grounded_rate,word_limit_ok_rate,instruction_following_rate
0,base,500,0.954,0.842,0.954,0.842
1,sft,500,1.000,0.960,1.000,0.960
2,dpo,500,0.846,0.800,0.846,0.800
3,ppo,500,1.000,0.952,1.000,0.952
4,grpo,500,1.000,0.948,1.000,0.948
5,qwen35_2b_fewshot,500,0.894,0.794,0.894,0.794
6,nlptown_template,500,1.000,1.000,1.000,1.000
7,deepseek_v4_pro_fewshot,500,0.948,0.938,0.948,0.938

Variants evaluated: base, sft, dpo, ppo, grpo, qwen35_2b_fewshot, nlptown_template, deepseek_v4_pro_fewshot
Report: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/report.md

## 11. Optional: AI Blind Judge

This step calls the OpenAI judge API and can incur API cost. It reuses existing prediction files and does not pass `--force-inference`.

In [16]:
RUN_AI_JUDGE = True
AI_JUDGE_SAMPLES_PER_PAIR = 100

if RUN_AI_JUDGE:
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError("Add OPENAI_API_KEY to Colab Secrets first.")
    cli(
        "evaluate",
        "--config",
        FORMAL_CONFIG,
        "--variants",
        *ALL_EVAL_VARIANTS,
        "--llm-judge",
        "--judge-samples-per-pair",
        str(AI_JUDGE_SAMPLES_PER_PAIR),
    )
    cli("build-report", "--config", FORMAL_CONFIG)
    display(pd.read_csv(FORMAL_ROOT / "evaluation" / "judge_pairwise_summary.csv"))
    print("Report:", FORMAL_ROOT / "evaluation" / "report.md")
else:
    print("Set RUN_AI_JUDGE = True to run blinded pairwise judging.")

$ /usr/bin/python3 -u -m amazon_review_alignment.cli evaluate --config configs/rlhf_a100_online_v2.yaml --variants base sft dpo ppo grpo qwen35_2b_fewshot nlptown_template deepseek_v4_pro_fewshot --llm-judge --judge-samples-per-pair 100
2026-07-16 17:49:25,141 | INFO | numexpr.utils | NumExpr defaulting to 12 threads.
2026-07-16 17:49:26,917 | INFO | amazon_review_alignment.inference | Reusing existing predictions: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/base.jsonl
2026-07-16 17:49:26,953 | INFO | amazon_review_alignment.inference | Reusing existing predictions: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/sft.jsonl
2026-07-16 17:49:26,990 | INFO | amazon_review_alignment.inference | Reusing existing predictions: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/dpo.jsonl
2026-07-16 17:49:27,025 | INFO | amazon_review_alignment.inference | Reusing existing predictions: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/ppo.jsonl
2026-07-16 17:49:27,060 | INFO | amazon_review_alignment.inference | Reusing existing predictions: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/grpo.jsonl
2026-07-16 17:49:27,082 | INFO | amazon_review_alignment.baselines | Reusing existing baseline predictions: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/qwen35_2b_fewshot.jsonl
2026-07-16 17:49:27,103 | INFO | amazon_review_alignment.baselines | Reusing existing baseline predictions: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/nlptown_template.jsonl
2026-07-16 17:49:27,123 | INFO | amazon_review_alignment.baselines | Reusing existing baseline predictions: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/predictions/deepseek_v4_pro_fewshot.jsonl
2026-07-16 17:49:28,200 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 10/100 (resumed)
2026-07-16 17:49:28,201 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 20/100 (resumed)
2026-07-16 17:49:28,201 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 30/100 (resumed)
2026-07-16 17:49:28,201 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 40/100 (resumed)
2026-07-16 17:49:28,201 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 50/100 (resumed)
2026-07-16 17:49:28,201 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 60/100 (resumed)
2026-07-16 17:49:28,201 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 70/100 (resumed)
2026-07-16 17:49:28,201 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 80/100 (resumed)
2026-07-16 17:49:28,201 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 90/100 (resumed)
2026-07-16 17:49:28,201 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_sft: 100/100 (resumed)
2026-07-16 17:49:28,202 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 10/100 (resumed)
2026-07-16 17:49:28,202 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 20/100 (resumed)
2026-07-16 17:49:28,202 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 30/100 (resumed)
2026-07-16 17:49:28,202 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 40/100 (resumed)
2026-07-16 17:49:28,203 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 50/100 (resumed)
2026-07-16 17:49:28,203 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 60/100 (resumed)
2026-07-16 17:49:28,203 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 70/100 (resumed)
2026-07-16 17:49:28,203 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 80/100 (resumed)
2026-07-16 17:49:28,203 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 90/100 (resumed)
2026-07-16 17:49:28,203 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_dpo: 100/100 (resumed)
2026-07-16 17:49:28,204 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 10/100 (resumed)
2026-07-16 17:49:28,204 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 20/100 (resumed)
2026-07-16 17:49:28,204 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 30/100 (resumed)
2026-07-16 17:49:28,205 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 40/100 (resumed)
2026-07-16 17:49:28,205 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 50/100 (resumed)
2026-07-16 17:49:28,205 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 60/100 (resumed)
2026-07-16 17:49:28,205 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 70/100 (resumed)
2026-07-16 17:49:28,205 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 80/100 (resumed)
2026-07-16 17:49:28,205 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 90/100 (resumed)
2026-07-16 17:49:28,206 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_ppo: 100/100 (resumed)
2026-07-16 17:49:28,206 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 10/100 (resumed)
2026-07-16 17:49:28,206 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 20/100 (resumed)
2026-07-16 17:49:28,207 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 30/100 (resumed)
2026-07-16 17:49:28,207 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 40/100 (resumed)
2026-07-16 17:49:28,207 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 50/100 (resumed)
2026-07-16 17:49:28,207 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 60/100 (resumed)
2026-07-16 17:49:28,207 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 70/100 (resumed)
2026-07-16 17:49:28,207 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 80/100 (resumed)
2026-07-16 17:49:28,208 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 90/100 (resumed)
2026-07-16 17:49:28,208 | INFO | amazon_review_alignment.evaluation | AI judge base_vs_grpo: 100/100 (resumed)
2026-07-16 17:49:28,208 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 10/100 (resumed)
2026-07-16 17:49:28,209 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 20/100 (resumed)
2026-07-16 17:49:28,209 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 30/100 (resumed)
2026-07-16 17:49:28,209 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 40/100 (resumed)
2026-07-16 17:49:28,209 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 50/100 (resumed)
2026-07-16 17:49:28,209 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 60/100 (resumed)
2026-07-16 17:49:28,210 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 70/100 (resumed)
2026-07-16 17:49:28,210 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 80/100 (resumed)
2026-07-16 17:49:28,210 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 90/100 (resumed)
2026-07-16 17:49:28,210 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_dpo: 100/100 (resumed)
2026-07-16 17:49:28,211 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 10/100 (resumed)
2026-07-16 17:49:28,211 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 20/100 (resumed)
2026-07-16 17:49:28,211 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 30/100 (resumed)
2026-07-16 17:49:28,211 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 40/100 (resumed)
2026-07-16 17:49:28,211 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 50/100 (resumed)
2026-07-16 17:49:28,212 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 60/100 (resumed)
2026-07-16 17:49:28,212 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 70/100 (resumed)
2026-07-16 17:49:28,212 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 80/100 (resumed)
2026-07-16 17:49:28,212 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 90/100 (resumed)
2026-07-16 17:49:28,212 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_ppo: 100/100 (resumed)
2026-07-16 17:49:28,213 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 10/100 (resumed)
2026-07-16 17:49:28,213 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 20/100 (resumed)
2026-07-16 17:49:28,213 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 30/100 (resumed)
2026-07-16 17:49:28,213 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 40/100 (resumed)
2026-07-16 17:49:28,214 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 50/100 (resumed)
2026-07-16 17:49:28,214 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 60/100 (resumed)
2026-07-16 17:49:28,214 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 70/100 (resumed)
2026-07-16 17:49:28,214 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 80/100 (resumed)
2026-07-16 17:49:28,214 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 90/100 (resumed)
2026-07-16 17:49:28,214 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_grpo: 100/100 (resumed)
2026-07-16 17:49:28,215 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 10/100 (resumed)
2026-07-16 17:49:28,215 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 20/100 (resumed)
2026-07-16 17:49:28,215 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 30/100 (resumed)
2026-07-16 17:49:28,216 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 40/100 (resumed)
2026-07-16 17:49:28,216 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 50/100 (resumed)
2026-07-16 17:49:28,216 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 60/100 (resumed)
2026-07-16 17:49:28,216 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 70/100 (resumed)
2026-07-16 17:49:28,216 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 80/100 (resumed)
2026-07-16 17:49:28,216 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 90/100 (resumed)
2026-07-16 17:49:28,217 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_ppo: 100/100 (resumed)
2026-07-16 17:49:28,217 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 10/100 (resumed)
2026-07-16 17:49:28,217 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 20/100 (resumed)
2026-07-16 17:49:28,218 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 30/100 (resumed)
2026-07-16 17:49:28,218 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 40/100 (resumed)
2026-07-16 17:49:28,218 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 50/100 (resumed)
2026-07-16 17:49:28,218 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 60/100 (resumed)
2026-07-16 17:49:28,218 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 70/100 (resumed)
2026-07-16 17:49:28,218 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 80/100 (resumed)
2026-07-16 17:49:28,219 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 90/100 (resumed)
2026-07-16 17:49:28,219 | INFO | amazon_review_alignment.evaluation | AI judge dpo_vs_grpo: 100/100 (resumed)
2026-07-16 17:49:28,219 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 10/100 (resumed)
2026-07-16 17:49:28,220 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 20/100 (resumed)
2026-07-16 17:49:28,220 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 30/100 (resumed)
2026-07-16 17:49:28,220 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 40/100 (resumed)
2026-07-16 17:49:28,220 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 50/100 (resumed)
2026-07-16 17:49:28,220 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 60/100 (resumed)
2026-07-16 17:49:28,220 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 70/100 (resumed)
2026-07-16 17:49:28,221 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 80/100 (resumed)
2026-07-16 17:49:28,221 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 90/100 (resumed)
2026-07-16 17:49:28,221 | INFO | amazon_review_alignment.evaluation | AI judge ppo_vs_grpo: 100/100 (resumed)
2026-07-16 17:49:31,098 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:33,050 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:36,130 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:38,891 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:41,768 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:43,047 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:46,778 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:48,009 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:49,191 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:50,665 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:50,670 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_qwen35_2b_fewshot: 10/100
2026-07-16 17:49:52,568 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:54,299 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:56,014 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:57,388 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:58,533 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:49:59,833 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:01,581 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:02,811 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:04,142 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:05,455 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:05,461 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_qwen35_2b_fewshot: 20/100
2026-07-16 17:50:07,032 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:08,543 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:10,026 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:11,685 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:13,241 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:14,616 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:16,102 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:17,156 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:18,425 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:19,611 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:19,616 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_qwen35_2b_fewshot: 30/100
2026-07-16 17:50:20,954 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:22,414 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:23,904 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:25,149 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:26,462 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:27,614 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:29,027 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:32,480 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:33,797 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:35,234 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:35,240 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_qwen35_2b_fewshot: 40/100
2026-07-16 17:50:36,428 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:37,907 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:39,024 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:40,322 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:41,774 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:43,169 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:44,472 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:45,776 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:47,269 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:49,185 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:49,190 | INFO | amazon_review_alignment.evaluation | AI judge sft_vs_qwen35_2b_fewshot: 50/100
2026-07-16 17:50:50,611 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:52,452 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:53,515 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:54,744 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:56,138 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
2026-07-16 17:50:57,495 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"

,comparison,examples,left_model,right_model,right_model_win_rate_ties_half,ci_95_low,ci_95_high,ties
0,base_vs_sft,100,base,sft,0.525,0.430000,0.615,5
1,base_vs_dpo,100,base,dpo,0.575,0.480000,0.670,5
2,base_vs_ppo,100,base,ppo,0.450,0.355000,0.545,4
3,base_vs_grpo,100,base,grpo,0.495,0.400000,0.590,7
4,sft_vs_dpo,100,sft,dpo,0.605,0.515000,0.695,13
5,sft_vs_ppo,100,sft,ppo,0.535,0.460000,0.610,43
6,sft_vs_grpo,100,sft,grpo,0.480,0.400000,0.560,30
7,dpo_vs_ppo,100,dpo,ppo,0.475,0.385000,0.560,21
8,dpo_vs_grpo,100,dpo,grpo,0.410,0.325000,0.495,22
9,ppo_vs_grpo,100,ppo,grpo,0.505,0.440000,0.570,57
10,sft_vs_qwen35_2b_fewshot,100,sft,qwen35_2b_fewshot,0.245,0.165000,0.330,5
11,dpo_vs_qwen35_2b_fewshot,100,dpo,qwen35_2b_fewshot,0.250,0.169875,0.335,2
12,dpo_vs_deepseek_v4_pro_fewshot,100,dpo,deepseek_v4_pro_fewshot,0.410,0.320000,0.510,0
13,ppo_vs_deepseek_v4_pro_fewshot,100,ppo,deepseek_v4_pro_fewshot,0.465,0.370000,0.560,7
14,grpo_vs_deepseek_v4_pro_fewshot,100,grpo,deepseek_v4_pro_fewshot,0.545,0.445000,0.640,5

Report: /content/drive/MyDrive/amazon-review-alignment-workspace/repo/outputs/a100-qwen3.5-2b/evaluation/report.md